package com.richardkenway.cavernreborn.core.worldgen;

public enum CaveniaPopulationStep {
    ENABLE_FALLING_INSTANTLY,
    PRE_CHUNK_POPULATE_EVENT,
    LAKE_BRANCHES,
    DECORATE_BIOME_PRE_EVENT,
    ORE_GEN_POST_EVENT,
    CAVENIC_SHROOM_BRANCH,
    FALL_LIQUID_BRANCHES,
    DECORATE_BIOME_POST_EVENT,
    POST_CHUNK_POPULATE_EVENT,
    DISABLE_FALLING_INSTANTLY
}
