package com.richardkenway.cavernreborn.core.worldgen;

public enum CaveniaGeneratorScaffoldStage {
    IDENTITY,
    BASE_TERRAIN,
    CAVE_CARVING,
    BIOME_TOP_FILTER_REPLACEMENT,
    VEINS_MUTATION,
    FINAL_CHUNK_CONSTRUCTION,
    POPULATION_INTEGRATION,
    SPAWN_PROVIDER_INTEGRATION_DEFERRED,
    ENTRY_ACCESS_DEFERRED
}
