package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRegistryLookupRequirement {
    CANDIDATE_KEYS_INVENTORIED,
    CANDIDATE_KEYS_STILL_STRING_ONLY,
    REGISTRY_ACCESS_SOURCE_DECISION,
    BIOME_REGISTRY_REFERENCE,
    RESOURCE_KEY_CONVERSION,
    HOLDER_RESOLUTION,
    MISSING_BIOME_FALLBACK_DECISION,
    RUNTIME_LOOKUP_CONTEXT,
    ADAPTER_RESULT_TO_RUNTIME_BIOME
}
