package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSubclassRequirement {
    SKELETON_READY,
    REAL_SUBCLASS_DEFERRED,
    ABSTRACT_METHODS_INVENTORY,
    CODEC_METHOD_SHAPE_DECISION,
    POSSIBLE_BIOMES_SHAPE_DECISION,
    NOISE_BIOME_QUERY_SHAPE_DECISION,
    HOLDER_RETURN_PATH_DECISION,
    REGISTRY_CONTEXT_DECISION,
    RESOURCE_KEY_CONVERSION_DECISION,
    MISSING_BIOME_FALLBACK_DECISION,
    NO_DIMENSION_ACTIVATION,
    NO_CODEC_REGISTRATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    NO_WORLDGEN_ACCESS_SPAWNING
}
