package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSubclassNextStepDecision {
    DEFER_REAL_BIOME_SOURCE_SUBCLASS_UNTIL_CODEC_HOLDER_REGISTRY_SHAPE_IS_PINNED,
    PROCEED_WITH_CODEC_HOLDER_REGISTRY_SHAPE_DECISION_NEXT,
    DEFER_DIMENSION_ACTIVATION,
    DEFER_CODEC_REGISTRATION,
    DEFER_REGISTRY_LOOKUP_ACCESS,
    DEFER_ACCESS_AND_SPAWNING
}
