package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceRuntimeConstructionFactoryGuardrail {
    ALLOW_RUNTIME_CONSTRUCTION_FACTORY_READINESS_NEXT,
    ALLOW_PRIVATE_CONSTRUCTOR_POLICY_PINNING_NEXT,
    ALLOW_FACTORY_METHOD_POLICY_PINNING_NEXT,
    ALLOW_PRE_RESOLVED_HOLDER_STATE_POLICY_PINNING_NEXT,
    ALLOW_HOLDER_SET_BUILDER_DEPENDENCY_PINNING_NEXT,
    ALLOW_LOOKUP_PROVIDER_INPUT_POLICY_PINNING_NEXT,
    ALLOW_IMMUTABLE_STATE_STORAGE_POLICY_PINNING_NEXT,
    ALLOW_COLLECT_POSSIBLE_BIOMES_STREAM_SOURCE_POLICY_PINNING_NEXT,
    ALLOW_NO_ACTIVATION_BOUNDARY_PINNING_NEXT,
    NO_RUNTIME_CONSTRUCTION_FACTORY_IMPLEMENTATION,
    NO_PUBLIC_CONSTRUCTOR,
    NO_FACTORY_METHOD,
    NO_PRE_RESOLVED_HOLDER_STATE,
    NO_COLLECT_POSSIBLE_BIOMES_WIRING,
    NO_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    NO_GET_NOISE_BIOME_WIRING,
    NO_GET_NOISE_BIOME_IMPLEMENTATION,
    NO_CODEC_OR_BIOME_SOURCE_TYPE_REGISTRATION,
    NO_GENERATOR_REGISTRATION,
    NO_DIMENSION_ACTIVATION,
    NO_WORLDGEN_ACCESS_SPAWNING,
    KEEP_RUNTIME_METHODS_UNSUPPORTED
}
