package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCandidateKeyToHolderConversionImplementationNextDecision {
    PROCEED_WITH_GUARDED_CANDIDATE_KEY_TO_HOLDER_CONVERSION_IMPLEMENTATION_NEXT,
    DEFER_GET_NOISE_BIOME_WIRING,
    DEFER_COLLECT_POSSIBLE_BIOMES_WIRING,
    DEFER_USABLE_RUNTIME_BIOME_SOURCE,
    DEFER_CODEC_REGISTRATION,
    DEFER_DIMENSION_ACTIVATION,
    DEFER_WORLDGEN_ACCESS_SPAWNING
}
