package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCodecMethodShapeComponent {
    LOCAL_CODEC_METHOD_SIGNATURE,
    DESIGNATED_SUBCLASS_OVERRIDE,
    UNSUPPORTED_CODEC_METHOD_BODY,
    NO_USABLE_MAP_CODEC,
    NO_STATIC_CODEC_FIELD,
    NO_RECORD_CODEC_BUILDER,
    NO_CODEC_REGISTRATION,
    NO_BIOME_SOURCE_TYPE_REGISTRATION,
    NO_REGISTRY_LOOKUP_DEPENDENCY,
    REAL_CODEC_STILL_DEFERRED
}
