package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorInputDerivationComponent {
    METHOD_INPUT_SHAPE,
    COORDINATE_INPUT_POLICY,
    CLIMATE_SAMPLER_INPUT_POLICY,
    SELECTOR_INPUT_OUTPUT_SHAPE,
    DETERMINISTIC_DERIVATION_POLICY,
    PURE_NON_RUNTIME_POLICY,
    WEIGHTED_SELECTOR_COMPATIBILITY,
    ADAPTER_QUERY_COMPATIBILITY,
    NORMALIZATION_POLICY,
    NEGATIVE_COORDINATE_STABILITY_POLICY,
    CHUNK_BOUNDARY_STABILITY_POLICY,
    NO_WORLD_OR_REGISTRY_DEPENDENCY,
    NO_RANDOM_OR_MUTABLE_STATE_DEPENDENCY,
    NO_SELECTOR_INPUT_DERIVATION_IMPLEMENTATION,
    NO_RUNTIME_SELECTION,
    REAL_SELECTOR_INPUT_DERIVATION_STILL_DEFERRED
}
