package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCandidateKeyToHolderConversionGuardrail {
    ALLOW_CANDIDATE_KEY_TO_HOLDER_CONVERSION_READINESS_NEXT,
    ALLOW_STRING_CANDIDATE_KEY_SURFACE_PINNING_NEXT,
    ALLOW_RESOURCE_\u004cOCATION_POLICY_PINNING_NEXT,
    ALLOW_RESOURCE_KEY_POLICY_PINNING_NEXT,
    ALLOW_REGISTRY_LOOKUP_POLICY_PINNING_NEXT,
    ALLOW_HOLDER_RESOLUTION_POLICY_PINNING_NEXT,
    ALLOW_MISSING_OR_FALLBACK_POLICY_PINNING_NEXT,
    NO_CANDIDATE_KEY_TO_HOLDER_CONVERSION_IMPLEMENTATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    NO_HOLDER_RESOLUTION,
    NO_RESOURCE_\u004cOCATION_CONVERSION,
    NO_RESOURCE_KEY_CONVERSION,
    NO_GET_NOISE_BIOME_WIRING,
    NO_GET_NOISE_BIOME_IMPLEMENTATION,
    NO_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    NO_FALLBACK_IMPLEMENTATION,
    NO_USABLE_CODEC_OR_REGISTRATION,
    NO_DIMENSION_ACTIVATION,
    NO_WORLDGEN_ACCESS_SPAWNING,
    KEEP_CANDIDATE_KEYS_STRING_ONLY
}
