package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCandidateKeyToHolderConverterConsolidationComponent {
    DESIGNATED_CONVERTER_EXISTS,
    CANDIDATE_KEY_TO_HOLDER_CONVERTER_READY,
    STRING_CANDIDATE_KEY_INPUT_READY,
    RESOURCE_LOCATION_PARSE_CONFINED,
    RESOURCE_KEY_CONSTRUCTION_CONFINED,
    BIOME_REGISTRY_LOOKUP_CONFINED,
    HOLDER_RESOLUTION_CONFINED,
    OPTIONAL_HOLDER_RESULT_READY,
    FALLBACK_HOLDER_ATTEMPT_READY,
    SERVER_GLOBAL_ACCESS_ABSENT,
    GET_NOISE_BIOME_WIRING_BLOCKED,
    COLLECT_POSSIBLE_BIOMES_WIRING_BLOCKED,
    CODEC_AND_REGISTRATION_BLOCKED,
    DIMENSION_WORLDGEN_ACCESS_SPAWNING_BLOCKED,
    NEXT_DECISION_SELECTED
}
