package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceReadinessChainNextDecision {
    PROCEED_WITH_SELECTOR_INPUT_DERIVATION_GO_NO_GO_NEXT,
    DEFER_SELECTOR_INPUT_DERIVATION_IMPLEMENTATION,
    DEFER_REGISTRY_LOOKUP_ACCESS,
    DEFER_HOLDER_RESOLUTION,
    DEFER_USABLE_RUNTIME_BIOME_SOURCE,
    DEFER_CODEC_REGISTRATION,
    DEFER_DIMENSION_ACTIVATION,
    DEFER_WORLDGEN_ACCESS_SPAWNING
}
