package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorToWeightedCandidateBridgeComponent {
    SELECTOR_INPUT_SOURCE,
    WEIGHTED_SELECTOR_SOURCE,
    ADAPTER_SOURCE,
    CANDIDATE_INVENTORY_SOURCE,
    SELECTOR_INPUT_SHAPE,
    TOTAL_WEIGHT_CONTRACT,
    NORMALIZATION_POLICY,
    CANDIDATE_KEY_OUTPUT_SHAPE,
    CANDIDATE_ENTRY_COUNT,
    FALLBACK_POLICY_DEPENDENCY,
    POSSIBLE_BIOMES_CONSTRAINT,
    NOISE_BIOME_SELECTION_DEPENDENCY,
    NO_BRIDGE_IMPLEMENTATION,
    NO_SELECTOR_OR_ADAPTER_CALLS,
    NO_RUNTIME_WIRING,
    REAL_SELECTOR_TO_WEIGHTED_CANDIDATE_BRIDGE_STILL_DEFERRED
}
