package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorToWeightedCandidateBridgeConsolidationComponent {
    PURE_SELECTOR_TO_WEIGHTED_CANDIDATE_BRIDGE_READY,
    SIGNED_INT_SELECTOR_INPUT_READY,
    WEIGHTED_SELECTOR_OR_ADAPTER_PATH_READY,
    STRING_CANDIDATE_KEY_OUTPUT_READY,
    CANDIDATE_INVENTORY_COMPATIBILITY_READY,
    SAMPLE_CANDIDATE_KEYS_VERIFIED,
    CANDIDATE_KEYS_REMAIN_STRING_ONLY,
    NO_GET_NOISE_BIOME_WIRING,
    NO_HOLDER_CONVERSION,
    NO_REGISTRY_LOOKUP_ACCESS,
    NO_RESOURCE_LOCATION_OR_KEY_CONVERSION,
    RUNTIME_SELECTION_BLOCKED,
    CODEC_AND_REGISTRATION_BLOCKED,
    DIMENSION_WORLDGEN_ACCESS_SPAWNING_BLOCKED,
    NEXT_DECISION_SELECTED
}
