package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCollectPossibleBiomesHolderSetComponent {
    CANDIDATE_INVENTORY_SOURCE,
    DESIGNATED_CONVERTER_DEPENDENCY,
    LOOKUP_PROVIDER_REQUIREMENT,
    PRE_RESOLVED_HOLDER_SET_POLICY,
    HOLDER_SET_OUTPUT_SHAPE,
    STREAM_RETURN_BOUNDARY,
    DEDUPLICATION_POLICY,
    ORDERING_POLICY,
    FALLBACK_IF_EMPTY_POLICY,
    MISSING_CANDIDATE_HANDLING_POLICY,
    INVALID_CANDIDATE_HANDLING_POLICY,
    UNRESOLVED_HOLDER_HANDLING_POLICY,
    NO_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    NO_CONVERTER_WIRING_IN_RUNTIME_METHODS,
    NO_GET_NOISE_BIOME_WIRING,
    NO_RUNTIME_CONSTRUCTION_OR_FACTORY,
    REAL_COLLECT_POSSIBLE_BIOMES_HOLDER_SET_STILL_DEFERRED
}
