package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceRealSubclassGuardrail {
    ALLOW_ONE_DESIGNATED_REAL_SUBCLASS_FILE_NEXT,
    ALLOW_BIOME_SOURCE_EXTENDS_ONLY_IN_DESIGNATED_SUBCLASS,
    ALLOW_ABSTRACT_METHOD_SIGNATURE_TYPES_ONLY,
    ALLOW_UNSUPPORTED_METHOD_STUBS_ONLY,
    NO_USABLE_CODEC_IMPLEMENTATION,
    NO_CODEC_REGISTRATION,
    NO_BIOME_SOURCE_TYPE_REGISTRATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    NO_HOLDER_RESOURCE_KEY_CONVERSION_IMPLEMENTATION,
    NO_DIMENSION_JSON,
    NO_DIMENSION_TYPE_JSON,
    NO_ACTIVE_CAVENIA_LEVEL,
    NO_WORLDGEN_RESOURCES,
    NO_ACCESS_OR_TELEPORT,
    NO_SPAWNING,
    NO_CAVEMAN_ENTITY_REGISTRATION,
    KEEP_SUBCLASS_UNREGISTERED_AND_UNREFERENCED_BY_RUNTIME,
    KEEP_EXISTING_SKELETON_AND_API_INVENTORY_INTACT
}
