package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorInputDerivationGuardrail {
    ALLOW_SELECTOR_INPUT_DERIVATION_READINESS_NEXT,
    ALLOW_COORDINATE_INPUT_POLICY_PINNING_NEXT,
    ALLOW_CLIMATE_SAMPLER_INPUT_POLICY_PINNING_NEXT,
    ALLOW_WEIGHT_VALUE_DERIVATION_POLICY_PINNING_NEXT,
    NO_SELECTOR_INPUT_DERIVATION_IMPLEMENTATION,
    NO_COORDINATE_RUNTIME_SELECTION,
    NO_CLIMATE_SAMPLER_RUNTIME_SELECTION,
    NO_GET_NOISE_BIOME_IMPLEMENTATION,
    NO_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    NO_HOLDER_RESOLUTION,
    NO_RESOURCE_LOCATION_OR_KEY_CONVERSION,
    NO_FALLBACK_IMPLEMENTATION,
    NO_USABLE_CODEC_OR_REGISTRATION,
    NO_DIMENSION_ACTIVATION,
    NO_WORLDGEN_ACCESS_SPAWNING,
    KEEP_READINESS_CHAIN_INERT
}
