package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorInputDerivationImplementationNextDecision {
    PROCEED_WITH_PURE_NON_RUNTIME_SELECTOR_INPUT_DERIVATION_ALGORITHM_NEXT,
    DEFER_RUNTIME_GET_NOISE_BIOME_WIRING,
    DEFER_CLIMATE_SAMPLER_CONSUMPTION,
    DEFER_REGISTRY_LOOKUP_ACCESS,
    DEFER_HOLDER_RESOLUTION,
    DEFER_USABLE_RUNTIME_BIOME_SOURCE,
    DEFER_CODEC_REGISTRATION,
    DEFER_DIMENSION_ACTIVATION,
    DEFER_WORLDGEN_ACCESS_SPAWNING
}
