package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceGuardrail {
    NO_DIMENSION_JSON,
    NO_DIMENSION_TYPE_JSON,
    NO_ACTIVE_CAVENIA_LEVEL,
    NO_CODEC_IMPLEMENTATION,
    NO_CODEC_REGISTRATION,
    NO_BIOME_SOURCE_TYPE_REGISTRATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    NO_BIOME_HOLDER_OR_RESOURCE_KEY_CONVERSION,
    NO_WORLDGEN_RESOURCES,
    NO_ACCESS_OR_TELEPORT,
    NO_SPAWNING,
    NO_CAVEMAN_ENTITY_REGISTRATION,
    UNREGISTERED_SKELETON_ONLY,
    KEEP_BIOME_SOURCE_STRATEGY_MATRIX_BLOCKED
}
