package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCollectPossibleBiomesHolderSetImplementationGuardrail {
    ALLOW_GUARDED_PRE_RESOLVED_HOLDER_SET_BUILDER_NEXT,
    ALLOW_CANDIDATE_INVENTORY_INPUT_NEXT,
    ALLOW_DESIGNATED_CONVERTER_DEPENDENCY_NEXT,
    ALLOW_LOOKUP_PROVIDER_PARAMETER_NEXT,
    ALLOW_RESOLVED_HOLDER_DEDUPLICATION_NEXT,
    ALLOW_LEGACY_ORDER_PRESERVATION_NEXT,
    ALLOW_FALLBACK_IF_EMPTY_NEXT,
    ALLOW_MISSING_INVALID_UNRESOLVED_SKIP_NEXT,
    NO_COLLECT_POSSIBLE_BIOMES_WIRING,
    NO_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    NO_GET_NOISE_BIOME_WIRING,
    NO_GET_NOISE_BIOME_IMPLEMENTATION,
    NO_RUNTIME_CONSTRUCTION_OR_FACTORY,
    NO_CODEC_OR_BIOME_SOURCE_TYPE_REGISTRATION,
    NO_GENERATOR_REGISTRATION,
    NO_DIMENSION_ACTIVATION,
    NO_WORLDGEN_ACCESS_SPAWNING,
    KEEP_RUNTIME_METHODS_UNSUPPORTED
}
