package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorToWeightedCandidateBridgeImplementationNextDecision {
    PROCEED_WITH_PURE_NON_RUNTIME_SELECTOR_TO_WEIGHTED_CANDIDATE_BRIDGE_NEXT,
    DEFER_GET_NOISE_BIOME_WIRING,
    DEFER_HOLDER_CONVERSION,
    DEFER_REGISTRY_LOOKUP_ACCESS,
    DEFER_USABLE_RUNTIME_BIOME_SOURCE,
    DEFER_CODEC_REGISTRATION,
    DEFER_DIMENSION_ACTIVATION,
    DEFER_WORLDGEN_ACCESS_SPAWNING
}
