package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceApiShapeComponent {
    LOCAL_BIOME_SOURCE_CLASS,
    ABSTRACT_METHODS_INVENTORY,
    CODEC_DISPATCH_SHAPE,
    CODEC_METHOD_SHAPE,
    POSSIBLE_BIOMES_SHAPE,
    NOISE_BIOME_QUERY_SHAPE,
    CLIMATE_SAMPLER_SHAPE,
    HOLDER_RETURN_SHAPE,
    REGISTRY_CONTEXT_SHAPE,
    RESOURCE_KEY_CONVERSION_SHAPE,
    MISSING_BIOME_FALLBACK_SHAPE,
    REAL_SUBCLASS_STILL_DEFERRED
}
