package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaBiomeSourceStrategyRequirement {
    LEGACY_WEIGHTED_BIOME_INPUTS,
    LEGACY_TO_MODERN_BIOME_KEY_MAPPING,
    WEIGHTED_SELECTION_ALGORITHM,
    TOP_BLOCK_STRATEGY,
    RUNTIME_BIOME_SOURCE_IMPLEMENTATION,
    BIOME_SOURCE_CODEC_AND_REGISTRATION,
    REGISTRY_LOOKUP_ACCESS
}
