package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceRuntimeConstructionFactoryNextDecision {
    PROCEED_WITH_RUNTIME_CONSTRUCTION_FACTORY_READINESS_NEXT,
    DEFER_RUNTIME_CONSTRUCTION_FACTORY_IMPLEMENTATION,
    DEFER_PUBLIC_FACTORY_METHOD,
    DEFER_PRE_RESOLVED_HOLDER_STATE,
    DEFER_COLLECT_POSSIBLE_BIOMES_WIRING,
    DEFER_GET_NOISE_BIOME_WIRING,
    DEFER_USABLE_RUNTIME_BIOME_SOURCE,
    DEFER_CODEC_REGISTRATION,
    DEFER_BIOME_SOURCE_TYPE_REGISTRATION,
    DEFER_GENERATOR_REGISTRATION,
    DEFER_DIMENSION_ACTIVATION,
    DEFER_WORLDGEN_ACCESS_SPAWNING
}
