package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCollectPossibleBiomesHolderSetGuardrail {
    ALLOW_COLLECT_POSSIBLE_BIOMES_HOLDER_SET_READINESS_NEXT,
    ALLOW_CANDIDATE_INVENTORY_SOURCE_PINNING_NEXT,
    ALLOW_CONVERTER_DEPENDENCY_PINNING_NEXT,
    ALLOW_HOLDER_SET_OUTPUT_POLICY_PINNING_NEXT,
    ALLOW_DEDUPLICATION_POLICY_PINNING_NEXT,
    ALLOW_ORDERING_POLICY_PINNING_NEXT,
    ALLOW_FALLBACK_IF_EMPTY_POLICY_PINNING_NEXT,
    ALLOW_MISSING_CANDIDATE_POLICY_PINNING_NEXT,
    ALLOW_STREAM_RETURN_BOUNDARY_PINNING_NEXT,
    NO_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    NO_COLLECT_POSSIBLE_BIOMES_WIRING,
    NO_GET_NOISE_BIOME_WIRING,
    NO_GET_NOISE_BIOME_IMPLEMENTATION,
    NO_CODEC_OR_BIOME_SOURCE_TYPE_REGISTRATION,
    NO_GENERATOR_REGISTRATION,
    NO_DIMENSION_ACTIVATION,
    NO_WORLDGEN_ACCESS_SPAWNING,
    KEEP_RUNTIME_METHODS_UNSUPPORTED
}
