package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorToWeightedCandidateBridgeImplementationComponent {
    SIGNED_INT_SELECTOR_INPUT,
    PURE_NON_RUNTIME_BRIDGE,
    WEIGHTED_SELECTOR_OR_ADAPTER_PATH,
    STRING_CANDIDATE_KEY_OUTPUT,
    CANDIDATE_INVENTORY_COMPATIBILITY,
    NORMALIZATION_DELEGATED_TO_SELECTOR_PATH,
    DETERMINISTIC_BRIDGE_OUTPUT,
    NO_MINECRAFT_RUNTIME_API_DEPENDENCY,
    NO_REGISTRY_OR_HOLDER_DEPENDENCY,
    NO_FALLBACK_RUNTIME_USAGE,
    NO_GET_NOISE_BIOME_WIRING,
    REAL_RUNTIME_SELECTION_STILL_DEFERRED
}
