package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourcePossibleBiomesComponent {
    POSSIBLE_BIOMES_METHOD_SHAPE,
    CANDIDATE_KEYS_SOURCE,
    CANDIDATE_ENTRY_COUNT,
    CANDIDATE_ORDERING_POLICY,
    CANDIDATE_DEDUPLICATION_POLICY,
    HOLDER_CONVERSION_DEPENDENCY,
    FALLBACK_POLICY_SOURCE,
    FALLBACK_INCLUDED_IF_EMPTY_POLICY,
    NO_RUNTIME_HOLDER_STREAM,
    NO_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    REAL_POSSIBLE_BIOMES_STILL_DEFERRED
}
