package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCandidateKeyToHolderConversionNextDecision {
    PROCEED_WITH_CANDIDATE_KEY_TO_HOLDER_CONVERSION_READINESS_NEXT,
    DEFER_CANDIDATE_KEY_TO_HOLDER_CONVERSION_IMPLEMENTATION,
    DEFER_REGISTRY_LOOKUP_ACCESS,
    DEFER_HOLDER_RESOLUTION,
    DEFER_RESOURCE_\u004cOCATION_CONVERSION,
    DEFER_RESOURCE_KEY_CONVERSION,
    DEFER_GET_NOISE_BIOME_WIRING,
    DEFER_USABLE_RUNTIME_BIOME_SOURCE,
    DEFER_CODEC_REGISTRATION,
    DEFER_DIMENSION_ACTIVATION,
    DEFER_WORLDGEN_ACCESS_SPAWNING
}
