package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorToWeightedCandidateBridgeImplementationGuardrail {
    ALLOW_PURE_NON_RUNTIME_BRIDGE_NEXT,
    ALLOW_SIGNED_INT_SELECTOR_INPUT_NEXT,
    ALLOW_EXISTING_WEIGHTED_SELECTOR_OR_ADAPTER_NEXT,
    ALLOW_STRING_CANDIDATE_KEY_OUTPUT_NEXT,
    ALLOW_CANDIDATE_INVENTORY_DATA_NEXT,
    NO_MINECRAFT_RUNTIME_API_IMPORTS,
    NO_GET_NOISE_BIOME_WIRING,
    NO_GET_NOISE_BIOME_IMPLEMENTATION,
    NO_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    NO_HOLDER_RESOLUTION,
    NO_RESOURCE_LOCATION_OR_KEY_CONVERSION,
    NO_FALLBACK_IMPLEMENTATION,
    NO_USABLE_CODEC_OR_REGISTRATION,
    NO_DIMENSION_ACTIVATION,
    NO_WORLDGEN_ACCESS_SPAWNING,
    KEEP_RUNTIME_METHODS_UNSUPPORTED
}
