package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorToWeightedCandidateBridgeGuardrail {
    ALLOW_SELECTOR_TO_WEIGHTED_CANDIDATE_BRIDGE_READINESS_NEXT,
    ALLOW_SELECTOR_INPUT_SURFACE_POLICY_PINNING_NEXT,
    ALLOW_WEIGHTED_SELECTOR_QUERY_POLICY_PINNING_NEXT,
    ALLOW_ADAPTER_QUERY_POLICY_PINNING_NEXT,
    ALLOW_CANDIDATE_KEY_OUTPUT_POLICY_PINNING_NEXT,
    NO_SELECTOR_TO_WEIGHTED_CANDIDATE_BRIDGE_IMPLEMENTATION,
    NO_WEIGHTED_SELECTOR_CALL_WITH_DERIVED_INPUT,
    NO_ADAPTER_CALL_WITH_DERIVED_INPUT,
    NO_GET_NOISE_BIOME_WIRING,
    NO_GET_NOISE_BIOME_IMPLEMENTATION,
    NO_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    NO_HOLDER_RESOLUTION,
    NO_RESOURCE_LOCATION_OR_KEY_CONVERSION,
    NO_FALLBACK_IMPLEMENTATION,
    NO_USABLE_CODEC_OR_REGISTRATION,
    NO_DIMENSION_ACTIVATION,
    NO_WORLDGEN_ACCESS_SPAWNING,
    KEEP_SELECTOR_INPUT_ALGORITHM_INERT
}
