package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorInputAlgorithmConsolidationNextDecision {
    PROCEED_WITH_SELECTOR_TO_WEIGHTED_CANDIDATE_BRIDGE_GO_NO_GO_NEXT,
    DEFER_SELECTOR_TO_WEIGHTED_CANDIDATE_BRIDGE_IMPLEMENTATION,
    DEFER_GET_NOISE_BIOME_WIRING,
    DEFER_REGISTRY_LOOKUP_ACCESS,
    DEFER_HOLDER_RESOLUTION,
    DEFER_USABLE_RUNTIME_BIOME_SOURCE,
    DEFER_CODEC_REGISTRATION,
    DEFER_DIMENSION_ACTIVATION,
    DEFER_WORLDGEN_ACCESS_SPAWNING
}
