package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorInputDerivationAlgorithmComponent {
    INTEGER_COORDINATE_INPUTS,
    CLIMATE_SAMPLER_EXCLUDED,
    PURE_NON_RUNTIME_ALGORITHM,
    DETERMINISTIC_MIXING_FORMULA,
    SIGNED_INT_SELECTOR_OUTPUT,
    NORMALIZATION_DELEGATED,
    NEGATIVE_COORDINATE_STABILITY,
    CHUNK_BOUNDARY_STABILITY,
    NO_WORLD_OR_REGISTRY_DEPENDENCY,
    NO_RANDOM_OR_MUTABLE_STATE,
    NO_GET_NOISE_BIOME_WIRING,
    REAL_RUNTIME_SELECTION_STILL_DEFERRED
}
