package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceNoiseBiomeSelectionComponent {
    NOISE_BIOME_METHOD_SHAPE,
    COORDINATE_INPUT_SHAPE,
    CLIMATE_SAMPLER_INPUT_SHAPE,
    WEIGHT_VALUE_DERIVATION_DECISION,
    WEIGHTED_SELECTION_SOURCE,
    ADAPTER_SELECTION_SOURCE,
    CANDIDATE_KEY_OUTPUT_SOURCE,
    HOLDER_CONVERSION_DEPENDENCY,
    FALLBACK_POLICY_SOURCE,
    POSSIBLE_BIOMES_CONSTRAINT,
    NO_RUNTIME_HOLDER_RETURN,
    NO_GET_NOISE_BIOME_IMPLEMENTATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    REAL_NOISE_BIOME_SELECTION_STILL_DEFERRED
}
