package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceHolderConversionComponent {
    STRING_CANDIDATE_KEYS_SOURCE,
    CANDIDATE_KEY_FORMAT_CONTRACT,
    RESOURCE_LOCATION_CONVERSION_DECISION,
    RESOURCE_KEY_CONVERSION_DECISION,
    BIOME_REGISTRY_LOOKUP_DECISION,
    HOLDER_RESOLUTION_DECISION,
    POSSIBLE_BIOMES_HOLDER_SET_DECISION,
    NOISE_BIOME_HOLDER_RETURN_DECISION,
    MISSING_BIOME_FALLBACK_DECISION,
    NO_RUNTIME_CONVERSION_IMPLEMENTATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    REAL_HOLDER_CONVERSION_STILL_DEFERRED
}
