package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCollectPossibleBiomesHolderSetBuilderComponent {
    DESIGNATED_BUILDER_FILE,
    CANDIDATE_INVENTORY_INPUT,
    LOOKUP_PROVIDER_PARAMETER,
    DESIGNATED_CONVERTER_USAGE,
    RESOLVED_HOLDER_COLLECTION,
    RESOLVED_HOLDER_DEDUPLICATION,
    LEGACY_ORDER_PRESERVATION,
    MISSING_INVALID_UNRESOLVED_SKIP,
    FALLBACK_IF_EMPTY,
    IMMUTABLE_OUTPUT_LIST,
    NO_COLLECT_POSSIBLE_BIOMES_WIRING,
    NO_GET_NOISE_BIOME_WIRING,
    REAL_RUNTIME_BIOME_SOURCE_STILL_DEFERRED
}
