package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCandidateKeyToHolderConversionComponent {
    STRING_CANDIDATE_KEY_INPUT,
    CANDIDATE_KEY_INVENTORY_SOURCE,
    RESOURCE_LOCATION_POLICY,
    RESOURCE_KEY_POLICY,
    BIOME_REGISTRY_LOOKUP_POLICY,
    HOLDER_RESOLUTION_POLICY,
    HOLDER_RETURN_BOUNDARY,
    MISSING_CANDIDATE_KEY_POLICY,
    UNRESOLVED_RESOURCE_LOCATION_POLICY,
    UNRESOLVED_RESOURCE_KEY_POLICY,
    MISSING_HOLDER_FALLBACK_POLICY,
    NO_CONVERSION_IMPLEMENTATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    REAL_CANDIDATE_KEY_TO_HOLDER_CONVERSION_STILL_DEFERRED
}
