package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceReadinessChainComponent {
    DESIGNATED_SUBCLASS_STUB,
    CODEC_METHOD_SHAPE_STUB,
    HOLDER_RESOURCE_KEY_CONVERSION_READINESS,
    FALLBACK_POLICY_READINESS,
    POSSIBLE_BIOMES_READINESS,
    NOISE_BIOME_SELECTION_READINESS,
    SELECTOR_INPUT_DERIVATION_NOT_PINNED,
    REGISTRY_LOOKUP_ACCESS_BLOCKED,
    HOLDER_RESOLUTION_BLOCKED,
    RESOURCE_LOCATION_CONVERSION_BLOCKED,
    RESOURCE_KEY_CONVERSION_BLOCKED,
    USABLE_RUNTIME_METHODS_BLOCKED,
    USABLE_CODEC_IMPLEMENTATION_BLOCKED,
    CODEC_AND_TYPE_REGISTRATION_BLOCKED,
    DIMENSION_ACTIVATION_BLOCKED,
    WORLDGEN_ACCESS_SPAWNING_BLOCKED,
    NEXT_DECISION_SELECTED
}
