package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorInputAlgorithmConsolidationComponent {
    PURE_SELECTOR_INPUT_ALGORITHM_READY,
    INTEGER_COORDINATE_INPUTS_READY,
    CLIMATE_SAMPLER_EXCLUDED,
    SIGNED_INT_SELECTOR_OUTPUT_READY,
    DETERMINISTIC_FORMULA_READY,
    NORMALIZATION_DELEGATED,
    NEGATIVE_COORDINATE_STABILITY_READY,
    NO_RANDOM_OR_MUTABLE_STATE,
    WEIGHTED_SELECTOR_COMPATIBILITY_READY,
    ADAPTER_COMPATIBILITY_READY,
    SELECTOR_TO_WEIGHTED_CANDIDATE_BRIDGE_NOT_IMPLEMENTED,
    GET_NOISE_BIOME_WIRING_BLOCKED,
    RUNTIME_SELECTION_BLOCKED,
    REGISTRY_AND_HOLDER_SURFACES_BLOCKED,
    NEXT_DECISION_SELECTED
}
