package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorInputDerivationImplementationGuardrail {
    ALLOW_PURE_NON_RUNTIME_ALGORITHM_NEXT,
    ALLOW_INTEGER_COORDINATE_INPUTS_NEXT,
    ALLOW_SIGNED_INT_SELECTOR_OUTPUT_NEXT,
    ALLOW_EXISTING_SELECTOR_NORMALIZATION_NEXT,
    NO_CLIMATE_SAMPLER_METHOD_CALLS,
    NO_MINECRAFT_RUNTIME_API_IMPORTS,
    NO_GET_NOISE_BIOME_WIRING,
    NO_GET_NOISE_BIOME_IMPLEMENTATION,
    NO_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    NO_REGISTRY_LOOKUP_ACCESS,
    NO_HOLDER_RESOLUTION,
    NO_RESOURCE_LOCATION_OR_KEY_CONVERSION,
    NO_FALLBACK_IMPLEMENTATION,
    NO_USABLE_CODEC_OR_REGISTRATION,
    NO_RANDOM_OR_MUTABLE_STATE,
    NO_DIMENSION_ACTIVATION,
    NO_WORLDGEN_ACCESS_SPAWNING,
    KEEP_READINESS_CHAIN_INERT
}
