package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaBiomeSourceStrategyPlanStep {
    CONFIRM_SELECTED_SURFACE,
    PIN_LEGACY_WEIGHTED_INPUTS,
    PIN_LEGACY_TOP_BLOCK_INPUTS,
    INVENTORY_LEGACY_TO_MODERN_BIOME_MAPPING,
    DEFER_WEIGHTED_SELECTION_ALGORITHM,
    DEFER_RUNTIME_BIOME_SOURCE,
    DEFER_CODEC_AND_REGISTRATION,
    DEFER_REGISTRY_LOOKUP_ACCESS
}
