package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCandidateKeyToHolderConversionImplementationGuardrail {
    ALLOW_GUARDED_CONVERSION_HELPER_NEXT,
    ALLOW_STRING_CANDIDATE_KEY_INPUT_NEXT,
    ALLOW_RESOURCE_\u004cOCATION_PARSING_IN_DESIGNATED_HELPER_NEXT,
    ALLOW_RESOURCE_KEY_CONSTRUCTION_IN_DESIGNATED_HELPER_NEXT,
    ALLOW_BIOME_REGISTRY_LOOKUP_IN_DESIGNATED_HELPER_NEXT,
    ALLOW_HOLDER_RESOLUTION_IN_DESIGNATED_HELPER_NEXT,
    ALLOW_MISSING_OR_FALLBACK_HANDLING_IN_DESIGNATED_HELPER_NEXT,
    NO_GET_NOISE_BIOME_WIRING,
    NO_GET_NOISE_BIOME_IMPLEMENTATION,
    NO_COLLECT_POSSIBLE_BIOMES_WIRING,
    NO_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    NO_CODEC_OR_BIOME_SOURCE_TYPE_REGISTRATION,
    NO_GENERATOR_REGISTRATION,
    NO_DIMENSION_ACTIVATION,
    NO_WORLDGEN_ACCESS_SPAWNING,
    KEEP_RUNTIME_METHODS_UNSUPPORTED
}
