package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCandidateKeyToHolderConverterComponent {
    DESIGNATED_CONVERTER_FILE,
    STRING_CANDIDATE_KEY_INPUT,
    RESOURCE_LOCATION_PARSE_STEP,
    BIOME_RESOURCE_KEY_STEP,
    BIOME_REGISTRY_LOOKUP_STEP,
    HOLDER_RESOLUTION_STEP,
    OPTIONAL_HOLDER_RESULT,
    FALLBACK_CANDIDATE_ATTEMPT,
    INVALID_OR_MISSING_KEY_HANDLING,
    NO_GET_NOISE_BIOME_WIRING,
    NO_COLLECT_POSSIBLE_BIOMES_WIRING,
    REAL_RUNTIME_BIOME_SOURCE_STILL_DEFERRED
}
