package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceFallbackPolicyComponent {
    FALLBACK_POLICY_SOURCE,
    FALLBACK_TRIGGER_UNPARSEABLE_CANDIDATE_ID,
    FALLBACK_TRIGGER_UNRESOLVED_RESOURCE_KEY,
    FALLBACK_TRIGGER_MISSING_HOLDER,
    FALLBACK_TRIGGER_EMPTY_POSSIBLE_BIOMES,
    FALLBACK_LEGACY_BIOME_NAME,
    FALLBACK_CANDIDATE_MODERN_KEY,
    FALLBACK_REGISTRY_VERIFICATION_DEFERRED,
    FALLBACK_HOLDER_RESOLUTION_DEFERRED,
    FALLBACK_RUNTIME_USAGE_DEFERRED,
    NO_RUNTIME_FALLBACK_IMPLEMENTATION,
    REAL_FALLBACK_POLICY_STILL_DEFERRED
}
