package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaWorldgenResourceRequirement {
    CONFIGURED_CARVER_MAPPING,
    CONFIGURED_FEATURE_MAPPING,
    PLACED_FEATURE_MAPPING,
    BIOME_MODIFIER_MAPPING,
    BIOME_TAG_MAPPING,
    VEINS_RESOURCE_MAPPING,
    POPULATION_RESOURCE_MAPPING,
    CAVENIC_SHROOM_CAVENIA_MAPPING,
    RESOURCE_ORDERING_GUARD,
    NO_CAVERN_RESOURCE_REUSE_AS_PARITY
}
