package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCollectPossibleBiomesHolderSetBuilderConsolidationComponent {
    DESIGNATED_BUILDER_EXISTS,
    HOLDER_SET_BUILDER_READY,
    CANDIDATE_INVENTORY_INPUT_READY,
    DESIGNATED_CONVERTER_DEPENDENCY_READY,
    LOOKUP_PROVIDER_PARAMETER_READY,
    PRE_RESOLVED_HOLDER_LIST_READY,
    DEDUPLICATION_READY,
    LEGACY_ORDER_PRESERVED,
    FALLBACK_IF_EMPTY_READY,
    IMMUTABLE_OUTPUT_READY,
    COLLECT_POSSIBLE_BIOMES_WIRING_BLOCKED,
    GET_NOISE_BIOME_WIRING_BLOCKED,
    RUNTIME_CONSTRUCTION_FACTORY_BLOCKED,
    CODEC_AND_REGISTRATION_BLOCKED,
    DIMENSION_WORLDGEN_ACCESS_SPAWNING_BLOCKED,
    NEXT_DECISION_SELECTED
}
