package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceSelectorInputDerivationNextDecision {
    PROCEED_WITH_SELECTOR_INPUT_DERIVATION_READINESS_NEXT,
    DEFER_SELECTOR_INPUT_DERIVATION_IMPLEMENTATION,
    DEFER_COORDINATE_RUNTIME_SELECTION,
    DEFER_CLIMATE_SAMPLER_RUNTIME_SELECTION,
    DEFER_GET_NOISE_BIOME_IMPLEMENTATION,
    DEFER_REGISTRY_LOOKUP_ACCESS,
    DEFER_HOLDER_RESOLUTION,
    DEFER_USABLE_RUNTIME_BIOME_SOURCE,
    DEFER_CODEC_REGISTRATION,
    DEFER_DIMENSION_ACTIVATION,
    DEFER_WORLDGEN_ACCESS_SPAWNING
}
