package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceCandidateKeyToHolderConverterConsolidationNextDecision {
    PROCEED_WITH_COLLECT_POSSIBLE_BIOMES_HOLDER_SET_GO_NO_GO_NEXT,
    DEFER_COLLECT_POSSIBLE_BIOMES_HOLDER_SET_READINESS,
    DEFER_COLLECT_POSSIBLE_BIOMES_IMPLEMENTATION,
    DEFER_GET_NOISE_BIOME_WIRING,
    DEFER_USABLE_RUNTIME_BIOME_SOURCE,
    DEFER_CODEC_REGISTRATION,
    DEFER_DIMENSION_ACTIVATION,
    DEFER_WORLDGEN_ACCESS_SPAWNING
}
