package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaRuntimeBiomeSourceRealSubclassNextStepDecision {
    PROCEED_WITH_GUARDED_UNREGISTERED_REAL_BIOME_SOURCE_SUBCLASS_NEXT,
    DEFER_USABLE_CODEC_IMPLEMENTATION,
    DEFER_CODEC_REGISTRATION,
    DEFER_BIOME_SOURCE_TYPE_REGISTRATION,
    DEFER_REGISTRY_LOOKUP_ACCESS,
    DEFER_HOLDER_RESOURCE_KEY_CONVERSION_IMPLEMENTATION,
    DEFER_DIMENSION_ACTIVATION,
    DEFER_WORLDGEN_ACCESS_SPAWNING
}
