package com.richardkenway.cavernreborn.app.worldgen;

public enum CaveniaFirstActiveSurfaceSelectionReason {
    PREREQUISITE_FOR_GENERATOR_HOST,
    PREREQUISITE_FOR_DIMENSION_BINDING,
    LOWER_RUNTIME_SIDE_EFFECT_RISK,
    DOES_NOT_REQUIRE_DIMENSION_JSON_YET,
    KEEPS_ACCESS_AND_SPAWN_BLOCKED,
    REQUIRES_FUTURE_EXPLICIT_RUNTIME_BIOME_SOURCE_MVP
}
