package com.richardkenway.cavernreborn.app.registry;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;

class CaveniaActiveFoundationReadinessPlanTest {
    private static final Path README = resolveProjectFile("README.md");
    private static final Path RUNTIME_SMOKE_DOC = resolveProjectFile("docs", "runtime-smoke.md");
    private static final Path PLAN_DOC = resolveProjectFile("docs", "cavenia-active-foundation-readiness-plan.md");
    private static final Path FOUNDATION_DOC = resolveProjectFile("docs", "cavenia-dimension-provider-foundation-boundary.md");
    private static final Path KEY_TYPE_DOC = resolveProjectFile("docs", "cavenia-dimension-key-type-contract-boundary.md");
    private static final Path BIOME_PROVIDER_DOC = resolveProjectFile("docs", "cavenia-biome-provider-contract-boundary.md");
    private static final Path VEINS_DOC = resolveProjectFile("docs", "cavenia-veins-content-pipeline-contract-boundary.md");
    private static final Path TERRAIN_DOC = resolveProjectFile("docs", "cavenia-chunk-generator-terrain-pipeline-contract-boundary.md");
    private static final Path CAVE_CARVER_DOC = resolveProjectFile("docs", "cavenia-cave-carver-mapgen-contract-boundary.md");
    private static final Path POPULATION_DOC = resolveProjectFile("docs", "cavenia-population-lakes-falls-shroom-contract-boundary.md");
    private static final Path ACCESS_DOC = resolveProjectFile("docs", "cavenia-mirage-entry-access-contract-boundary.md");
    private static final Path SPAWN_PROVIDER_DOC = resolveProjectFile("docs", "cavenia-spawn-provider-crazy-roster-activation-contract-boundary.md");
    private static final Path POLICY_DOC = resolveProjectFile("docs", "cavenia-spawn-provider-policy-mvp.md");
    private static final Path CRAZY_ROSTER_DOC = resolveProjectFile("docs", "cavenia-crazy-roster-natural-spawn-boundary.md");
    private static final Path CAVEMAN_DOC = resolveProjectFile("docs", "caveman-cavenia-normal-roster-boundary.md");
    private static final Path SCAFFOLD_DOC = resolveProjectFile("docs", "cavenia-runtime-key-inactive-dimension-scaffold-mvp.md");
    private static final Path TERRAIN_POLICY_DOC = resolveProjectFile("docs", "cavenia-terrain-generator-foundation-non-runtime-mvp.md");
    private static final Path CAVE_CARVER_POLICY_DOC = resolveProjectFile("docs", "cavenia-cave-carver-policy-non-runtime-mvp.md");
    private static final Path BIOME_TOP_FILTER_POLICY_DOC = resolveProjectFile("docs", "cavenia-biome-top-filter-policy-non-runtime-mvp.md");
    private static final Path VEINS_POLICY_DOC = resolveProjectFile("docs", "cavenia-veins-content-policy-non-runtime-mvp.md");
    private static final Path POPULATION_POLICY_DOC = resolveProjectFile("docs", "cavenia-population-policy-non-runtime-mvp.md");
    private static final Path GENERATOR_SCAFFOLD_DOC = resolveProjectFile("docs", "cavenia-active-generator-technical-scaffold-mvp.md");
    private static final Path GENERATOR_BRIDGE_DOC = resolveProjectFile("docs", "cavenia-active-generator-runtime-prototype-inert-bridge-mvp.md");
    private static final Path GENERATOR_REGISTRATION_DOC = resolveProjectFile("docs", "cavenia-active-generator-registration-inert-boundary-mvp.md");
    private static final Path GENERATOR_SKELETON_DOC = resolveProjectFile("docs", "cavenia-generator-biome-source-unregistered-skeleton-mvp.md");
    private static final Path GENERATOR_RUNTIME_CONTRACTS_DOC = resolveProjectFile("docs", "cavenia-generator-runtime-contracts-non-registered-mvp.md");
    private static final Path ACTIVATION_HOSTS_DOC = resolveProjectFile("docs", "cavenia-generator-activation-readiness-host-contracts-mvp.md");

    @Test
    void readinessPlanExistsAndPinsTheCurrentInactiveFoundationState() throws IOException {
        String readme = Files.readString(README);
        String runtimeSmokeDoc = Files.readString(RUNTIME_SMOKE_DOC);
        String planDoc = Files.readString(PLAN_DOC);
        String foundationDoc = Files.readString(FOUNDATION_DOC);
        String keyTypeDoc = Files.readString(KEY_TYPE_DOC);
        String biomeProviderDoc = Files.readString(BIOME_PROVIDER_DOC);
        String veinsDoc = Files.readString(VEINS_DOC);
        String terrainDoc = Files.readString(TERRAIN_DOC);
        String caveCarverDoc = Files.readString(CAVE_CARVER_DOC);
        String populationDoc = Files.readString(POPULATION_DOC);
        String accessDoc = Files.readString(ACCESS_DOC);
        String spawnProviderDoc = Files.readString(SPAWN_PROVIDER_DOC);
        String policyDoc = Files.readString(POLICY_DOC);
        String crazyRosterDoc = Files.readString(CRAZY_ROSTER_DOC);
        String cavemanDoc = Files.readString(CAVEMAN_DOC);
        String scaffoldDoc = Files.readString(SCAFFOLD_DOC);
        String terrainPolicyDoc = Files.readString(TERRAIN_POLICY_DOC);
        String caveCarverPolicyDoc = Files.readString(CAVE_CARVER_POLICY_DOC);
        String biomeTopFilterPolicyDoc = Files.readString(BIOME_TOP_FILTER_POLICY_DOC);
        String veinsPolicyDoc = Files.readString(VEINS_POLICY_DOC);
        String populationPolicyDoc = Files.readString(POPULATION_POLICY_DOC);
        String generatorScaffoldDoc = Files.readString(GENERATOR_SCAFFOLD_DOC);

        assertTrue(planDoc.contains("Cavenia Active Foundation Readiness / Implementation Plan"));
        assertTrue(planDoc.contains("docs/cavenia-dimension-provider-foundation-boundary.md"));
        assertTrue(planDoc.contains("docs/cavenia-dimension-key-type-contract-boundary.md"));
        assertTrue(planDoc.contains("docs/cavenia-biome-provider-contract-boundary.md"));
        assertTrue(planDoc.contains("docs/cavenia-veins-content-pipeline-contract-boundary.md"));
        assertTrue(planDoc.contains("docs/cavenia-chunk-generator-terrain-pipeline-contract-boundary.md"));
        assertTrue(planDoc.contains("docs/cavenia-cave-carver-mapgen-contract-boundary.md"));
        assertTrue(planDoc.contains("docs/cavenia-population-lakes-falls-shroom-contract-boundary.md"));
        assertTrue(planDoc.contains("docs/cavenia-mirage-entry-access-contract-boundary.md"));
        assertTrue(planDoc.contains("docs/cavenia-spawn-provider-crazy-roster-activation-contract-boundary.md"));
        assertTrue(planDoc.contains("docs/cavenia-spawn-provider-policy-mvp.md"));
        assertTrue(planDoc.contains("docs/cavenia-crazy-roster-natural-spawn-boundary.md"));
        assertTrue(planDoc.contains("docs/caveman-cavenia-normal-roster-boundary.md"));
        assertTrue(planDoc.contains("docs/cavenia-terrain-generator-foundation-non-runtime-mvp.md"));
        assertTrue(planDoc.contains("docs/cavenia-cave-carver-policy-non-runtime-mvp.md"));
        assertTrue(planDoc.contains("docs/cavenia-biome-top-filter-policy-non-runtime-mvp.md"));
        assertTrue(planDoc.contains("docs/cavenia-veins-content-policy-non-runtime-mvp.md"));
        assertTrue(planDoc.contains("docs/cavenia-population-policy-non-runtime-mvp.md"));
        assertTrue(planDoc.contains("docs/cavenia-active-generator-technical-scaffold-mvp.md"));
        assertTrue(planDoc.contains("docs/cavenia-active-generator-runtime-prototype-inert-bridge-mvp.md"));
        assertTrue(planDoc.contains("docs/cavenia-active-generator-registration-inert-boundary-mvp.md"));
        assertTrue(planDoc.contains("docs/cavenia-generator-biome-source-unregistered-skeleton-mvp.md"));
        assertTrue(planDoc.contains("docs/cavenia-generator-runtime-contracts-non-registered-mvp.md"));
        assertTrue(planDoc.contains("docs/cavenia-generator-activation-readiness-host-contracts-mvp.md"));
        assertTrue(planDoc.contains("`CaveniaSpawnProviderPolicy`"));
        assertTrue(planDoc.contains("`CaveniaSpawnEntry`"));
        assertTrue(planDoc.contains("`CaveniaTerrainGeneratorPolicy`"));
        assertTrue(planDoc.contains("`CaveniaTerrainStep`"));
        assertTrue(planDoc.contains("`CaveniaCaveCarverPolicy`"));
        assertTrue(planDoc.contains("`CaveniaCaveCarverReplacement`"));
        assertTrue(planDoc.contains("`CaveniaBiomeTopFilterPolicy`"));
        assertTrue(planDoc.contains("`CaveniaBiomeEntry`"));
        assertTrue(planDoc.contains("`CaveniaVeinsContentPolicy`"));
        assertTrue(planDoc.contains("`CaveniaVeinEntry`"));
        assertTrue(planDoc.contains("`CaveniaVeinBiomeFilterMode`"));
        assertTrue(planDoc.contains("`CaveniaPopulationPolicy`"));
        assertTrue(planDoc.contains("`CaveniaPopulationStep`"));
        assertTrue(planDoc.contains("`CaveniaPopulationBranch`"));
        assertTrue(planDoc.contains("`CaveniaGeneratorScaffold`"));
        assertTrue(planDoc.contains("`CaveniaGeneratorScaffoldStage`"));
        assertTrue(planDoc.contains("`CaveniaGeneratorSkeleton`"));
        assertTrue(planDoc.contains("`CaveniaBiomeSelectionSkeleton`"));
        assertTrue(planDoc.contains("`CaveniaGeneratorRuntimeOperation`"));
        assertTrue(planDoc.contains("`CaveniaGeneratorRuntimeOperationContract`"));
        assertTrue(planDoc.contains("`CaveniaGeneratorRuntimeContracts`"));
        assertTrue(planDoc.contains("`CaveniaActivationReadinessHost`"));
        assertTrue(planDoc.contains("`CaveniaActivationReadinessHostContract`"));
        assertTrue(planDoc.contains("`CaveniaActivationReadinessHosts`"));
        assertTrue(planDoc.contains("`EntityCaveman -> deferred:caveman`"));
        assertTrue(planDoc.contains("nearby `ICavenicMob` whose `isNonBoss()` returns `false`"));
        assertTrue(planDoc.contains("docs/cavenia-active-foundation-technical-spike.md"));
        assertTrue(planDoc.contains("`dimension/cavenia.json`"));
        assertTrue(planDoc.contains("`dimension_type/cavenia.json`"));
        assertTrue(planDoc.contains("`CAVENIA_LOCATION`"));
        assertTrue(planDoc.contains("`CAVENIA_LEVEL_KEY`"));
        assertTrue(planDoc.contains("docs/cavenia-runtime-key-inactive-dimension-scaffold-mvp.md"));
        assertTrue(planDoc.contains("no active Cavenia spawning"));
        assertTrue(planDoc.contains("no fake normal `CAVERN` crazy spawning"));
        assertTrue(planDoc.contains("Phase 0: Completed readiness inputs"));
        assertTrue(planDoc.contains("Phase 1: Active Cavenia key/type and inactive runtime identity MVP"));
        assertTrue(planDoc.contains("Phase 2: Minimal terrain/generator MVP"));
        assertTrue(planDoc.contains("Phase 3: Cave carver MVP"));
        assertTrue(planDoc.contains("Phase 4: Biome provider and surface/top/filter MVP"));
        assertTrue(planDoc.contains("Phase 5: VEINS/content MVP"));
        assertTrue(planDoc.contains("Phase 6: Population MVP"));
        assertTrue(planDoc.contains("Phase 7: Entry/access MVP"));
        assertTrue(planDoc.contains("Phase 8: Spawn provider MVP"));
        assertTrue(planDoc.contains("Phase 9: Caveman full parity"));
        assertTrue(planDoc.contains("First Active MVP Candidate"));
        assertTrue(planDoc.contains("`Cavenia Runtime Key / Inactive Dimension Scaffold MVP`"));
        assertTrue(planDoc.contains("Minimum Acceptance Checklist Before Enabling Cavenia"));
        assertTrue(planDoc.contains("active dimension key/type agreed"));
        assertTrue(planDoc.contains("safe generator strategy agreed"));
        assertTrue(planDoc.contains("no broken teleport/access path"));
        assertTrue(planDoc.contains("no fake `CAVERN` spawn path"));
        assertTrue(planDoc.contains("spawn provider consumes the non-runtime policy"));
        assertTrue(planDoc.contains("Caveman handling explicitly decided"));
        assertTrue(planDoc.contains("validation loop green"));

        assertTrue(readme.contains("Cavenia Active Foundation Readiness / Implementation Plan"));
        assertTrue(readme.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(readme.contains("Cavenia Active Foundation Technical Spike"));
        assertTrue(readme.contains("docs/cavenia-active-foundation-technical-spike.md"));
        assertTrue(readme.contains("Cavenia Runtime Key / Inactive Dimension Scaffold MVP"));
        assertTrue(readme.contains("docs/cavenia-runtime-key-inactive-dimension-scaffold-mvp.md"));
        assertTrue(readme.contains("Cavenia Terrain Generator Foundation / Non-Runtime MVP"));
        assertTrue(readme.contains("docs/cavenia-terrain-generator-foundation-non-runtime-mvp.md"));
        assertTrue(readme.contains("Cavenia Cave Carver Policy / Non-Runtime MVP"));
        assertTrue(readme.contains("docs/cavenia-cave-carver-policy-non-runtime-mvp.md"));
        assertTrue(readme.contains("Cavenia Biome Top/Filter Policy / Non-Runtime MVP"));
        assertTrue(readme.contains("docs/cavenia-biome-top-filter-policy-non-runtime-mvp.md"));
        assertTrue(readme.contains("Cavenia VEINS / Content Policy / Non-Runtime MVP"));
        assertTrue(readme.contains("docs/cavenia-veins-content-policy-non-runtime-mvp.md"));
        assertTrue(readme.contains("Cavenia Population Policy / Non-Runtime MVP"));
        assertTrue(readme.contains("docs/cavenia-population-policy-non-runtime-mvp.md"));
        assertTrue(readme.contains("Cavenia Active Generator Technical Scaffold / MVP"));
        assertTrue(readme.contains("docs/cavenia-active-generator-technical-scaffold-mvp.md"));
        assertTrue(readme.contains("docs/cavenia-active-generator-runtime-prototype-inert-bridge-mvp.md"));
        assertTrue(readme.contains("Cavenia Active Generator Registration / Inert Activation Boundary MVP"));
        assertTrue(readme.contains("docs/cavenia-active-generator-registration-inert-boundary-mvp.md"));
        assertTrue(readme.contains("Cavenia Chunk Generator / Biome Source Unregistered Skeleton MVP"));
        assertTrue(readme.contains("docs/cavenia-generator-biome-source-unregistered-skeleton-mvp.md"));
        assertTrue(readme.contains("Cavenia Generator Runtime Contract Interfaces / Non-Registered MVP"));
        assertTrue(readme.contains("docs/cavenia-generator-runtime-contracts-non-registered-mvp.md"));
        assertTrue(readme.contains("Cavenia Generator Activation-Readiness Runtime Host Contracts MVP"));
        assertTrue(readme.contains("docs/cavenia-generator-activation-readiness-host-contracts-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Active Foundation Readiness / Implementation Plan"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(runtimeSmokeDoc.contains("inactive Cavenia active-foundation readiness-plan boundary"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Active Foundation Technical Spike"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-active-foundation-technical-spike.md"));
        assertTrue(runtimeSmokeDoc.contains("inactive Cavenia active-foundation technical-spike boundary"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Runtime Key / Inactive Dimension Scaffold MVP"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-runtime-key-inactive-dimension-scaffold-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("inert Cavenia runtime-key / inactive-dimension scaffold MVP"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Terrain Generator Foundation / Non-Runtime MVP"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-terrain-generator-foundation-non-runtime-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("non-runtime Cavenia terrain-generator foundation MVP"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Cave Carver Policy / Non-Runtime MVP"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-cave-carver-policy-non-runtime-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("non-runtime Cavenia cave-carver policy MVP"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Biome Top/Filter Policy / Non-Runtime MVP"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-biome-top-filter-policy-non-runtime-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("non-runtime Cavenia biome top/filter policy MVP"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia VEINS / Content Policy / Non-Runtime MVP"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-veins-content-policy-non-runtime-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("non-runtime Cavenia VEINS/content policy MVP"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Population Policy / Non-Runtime MVP"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-population-policy-non-runtime-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("non-runtime Cavenia population policy MVP"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Active Generator Technical Scaffold / MVP"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-active-generator-technical-scaffold-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-active-generator-runtime-prototype-inert-bridge-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Active Generator Registration / Inert Activation Boundary MVP"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-active-generator-registration-inert-boundary-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Chunk Generator / Biome Source Unregistered Skeleton MVP"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-generator-biome-source-unregistered-skeleton-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Generator Runtime Contract Interfaces / Non-Registered MVP"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-generator-runtime-contracts-non-registered-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("Cavenia Generator Activation-Readiness Runtime Host Contracts MVP"));
        assertTrue(runtimeSmokeDoc.contains("docs/cavenia-generator-activation-readiness-host-contracts-mvp.md"));
        assertTrue(runtimeSmokeDoc.contains("non-registered Cavenia activation-readiness host-contract MVP"));
        assertTrue(Files.readString(GENERATOR_BRIDGE_DOC).contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(Files.readString(GENERATOR_REGISTRATION_DOC).contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(Files.readString(GENERATOR_SKELETON_DOC).contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(Files.readString(GENERATOR_RUNTIME_CONTRACTS_DOC).contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(Files.readString(ACTIVATION_HOSTS_DOC).contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(runtimeSmokeDoc.contains("non-registered Cavenia active-generator technical scaffold MVP"));
        assertTrue(scaffoldDoc.contains("Cavenia Runtime Key / Inactive Dimension Scaffold MVP"));
        assertTrue(terrainPolicyDoc.contains("Cavenia Terrain Generator Foundation / Non-Runtime MVP"));
        assertTrue(caveCarverPolicyDoc.contains("Cavenia Cave Carver Policy / Non-Runtime MVP"));
        assertTrue(biomeTopFilterPolicyDoc.contains("Cavenia Biome Top/Filter Policy / Non-Runtime MVP"));
        assertTrue(veinsPolicyDoc.contains("Cavenia VEINS / Content Policy / Non-Runtime MVP"));
        assertTrue(populationPolicyDoc.contains("Cavenia Population Policy / Non-Runtime MVP"));
        assertTrue(generatorScaffoldDoc.contains("Cavenia Active Generator Technical Scaffold / MVP"));

        assertTrue(foundationDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(keyTypeDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(biomeProviderDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(veinsDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(terrainDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(caveCarverDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(populationDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(accessDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(spawnProviderDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(policyDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(crazyRosterDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(cavemanDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(terrainPolicyDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(caveCarverPolicyDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(biomeTopFilterPolicyDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(veinsPolicyDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(populationPolicyDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(generatorScaffoldDoc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(Files.readString(GENERATOR_REGISTRATION_DOC).contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(Files.readString(GENERATOR_RUNTIME_CONTRACTS_DOC).contains("docs/cavenia-active-foundation-readiness-plan.md"));
    }

    private static Path resolveProjectFile(String first, String... more) {
        Path current = Path.of("").toAbsolutePath();

        for (int i = 0; i < 5 && current != null; i++) {
            Path candidate = current.resolve(Path.of(first, more));
            if (Files.exists(candidate)) {
                return candidate;
            }
            current = current.getParent();
        }

        throw new IllegalStateException("Could not resolve project file: " + Path.of(first, more));
    }
}
