package com.richardkenway.cavernreborn.app.gametest;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;

class CavernRuntimeSmokeDocumentationTest {
    private static final Path README = resolveProjectFile("README.md");
    private static final Path RUNTIME_SMOKE = resolveProjectFile("docs", "runtime-smoke.md");
    private static final Path SCRIPT = resolveProjectFile("scripts", "runtime-smoke.sh");

    @Test
    void readmeDocumentsAutomatedRuntimeSmokeEntryPoint() throws IOException {
        String readme = Files.readString(README);

        assertTrue(readme.contains("Automated Runtime Validation"));
        assertTrue(readme.contains("NeoForge GameTest"));
        assertTrue(readme.contains("docs/runtime-smoke.md"));
        assertTrue(readme.contains("./gradlew --no-daemon :app-neoforge:runGameTestServer"));
        assertTrue(readme.contains("scripts/runtime-smoke.sh"));
        assertTrue(readme.contains("hexcite"));
        assertTrue(readme.contains("randomite"));
        assertTrue(readme.contains("fissured_stone"));
        assertTrue(readme.contains("Mining Assist"));
        assertTrue(readme.contains("Miner's Orb MVP"));
        assertTrue(readme.contains("docs/miner-orb-mvp.md"));
        assertTrue(readme.contains("Ore Compass MVP"));
        assertTrue(readme.contains("docs/ore-compass-mvp.md"));
        assertTrue(readme.contains("bounded tracking UX follow-up"));
        assertTrue(readme.contains("track that target visually"));
        assertTrue(readme.contains("Hexcite Armor MVP"));
        assertTrue(readme.contains("docs/hexcite-armor-mvp.md"));
        assertTrue(readme.contains("Aquamarine Utility Tools MVP"));
        assertTrue(readme.contains("docs/aquamarine-tool-mvp.md"));
        assertTrue(readme.contains("Magnite Tool Set MVP"));
        assertTrue(readme.contains("docs/magnite-tool-mvp.md"));
        assertTrue(readme.contains("Magnite Armor MVP"));
        assertTrue(readme.contains("docs/magnite-armor-mvp.md"));
        assertTrue(readme.contains("Acresia Crop & Food MVP"));
        assertTrue(readme.contains("docs/acresia-crop-mvp.md"));
        assertTrue(readme.contains("renewable cave snack crop"));
        assertTrue(readme.contains("full farming system"));
        assertTrue(readme.contains("Cavenic Shroom & Orb MVP"));
        assertTrue(readme.contains("docs/cavenic-shroom-mvp.md"));
        assertTrue(readme.contains("hazardous flora"));
        assertTrue(readme.contains("Cavenic Bow Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-bow-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Bow Mode State & Cycling MVP"));
        assertTrue(readme.contains("docs/cavenic-bow-mode-state-mvp.md"));
        assertTrue(readme.contains("Cavenic Bow Snipe Mode MVP"));
        assertTrue(readme.contains("docs/cavenic-bow-snipe-mode-mvp.md"));
        assertTrue(readme.contains("Cavenic Bow Rapid Mode MVP"));
        assertTrue(readme.contains("docs/cavenic-bow-rapid-mode-mvp.md"));
        assertTrue(readme.contains("Cavenic Bow Rapid Low-Armor Hurt-Resistance MVP"));
        assertTrue(readme.contains("docs/cavenic-bow-rapid-low-armor-hurt-resistance-mvp.md"));
        assertTrue(readme.contains("Cavenic Bow Torch Mode MVP"));
        assertTrue(readme.contains("docs/cavenic-bow-torch-mode-mvp.md"));
        assertTrue(readme.contains("docs/cavenic-bow-torch-item-use-forwarding-boundary.md"));
        assertTrue(readme.contains("docs/entity-cavenic-arrow-projectile-boundary.md"));
        assertTrue(readme.contains("docs/entity-rapid-torch-arrow-projectile-boundary.md"));
        assertTrue(readme.contains("EntityRapidArrow"));
        assertTrue(readme.contains("EntityTorchArrow"));
        assertTrue(readme.contains("Cavenic Zombie Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-zombie-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Zombie Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-zombie-natural-spawn-mvp.md"));
        assertTrue(readme.contains("Cavenic Zombie Legacy Orb Drop MVP"));
        assertTrue(readme.contains("docs/cavenic-zombie-orb-drop-mvp.md"));
        assertTrue(readme.contains("Cavenic Zombie Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-zombie-damage-behavior-mvp.md"));
        assertTrue(readme.contains("legacy `1/8` `cavenic_orb` drop"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity"));
        assertTrue(readme.contains("Cavenic Skeleton Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-skeleton-baseline-mvp.md"));
        assertTrue(readme.contains("second direct Cavenic mob foundation"));
        assertTrue(readme.contains("Cavenic Skeleton Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-skeleton-natural-spawn-mvp.md"));
        assertTrue(readme.contains("bounded CAVERN-only natural spawning"));
        assertTrue(readme.contains("Cavenic Skeleton Legacy Orb Drop MVP"));
        assertTrue(readme.contains("docs/cavenic-skeleton-orb-drop-mvp.md"));
        assertTrue(readme.contains("legacy `1/5` `cavenic_orb` drop"));
        assertTrue(readme.contains("Cavenic Skeleton Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-skeleton-damage-behavior-mvp.md"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity"));
        assertTrue(readme.contains("Cavenic Creeper Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-creeper-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Creeper Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-creeper-natural-spawn-mvp.md"));
        assertTrue(readme.contains("Cavenic Creeper Legacy Orb Drop MVP"));
        assertTrue(readme.contains("docs/cavenic-creeper-orb-drop-mvp.md"));
        assertTrue(readme.contains("Cavenic Creeper Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-creeper-damage-behavior-mvp.md"));
        assertTrue(readme.contains("Cavenic Creeper Legacy Fuse/Explosion MVP"));
        assertTrue(readme.contains("docs/cavenic-creeper-fuse-explosion-mvp.md"));
        assertTrue(readme.contains("third direct Cavenic mob foundation"));
        assertTrue(readme.contains("bounded CAVERN-only natural spawning"));
        assertTrue(readme.contains("legacy `1/5` `cavenic_orb` drop"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity"));
        assertTrue(readme.contains("legacy `Fuse = 15` and `ExplosionRadius = 5`"));
        assertTrue(readme.contains("Cavenic Spider Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-spider-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Spider Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-spider-natural-spawn-mvp.md"));
        assertTrue(readme.contains("Cavenic Spider Legacy Orb Drop MVP"));
        assertTrue(readme.contains("docs/cavenic-spider-orb-drop-mvp.md"));
        assertTrue(readme.contains("Cavenic Spider Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-spider-damage-behavior-mvp.md"));
        assertTrue(readme.contains("Cavenic Spider Blindness-On-Hit MVP"));
        assertTrue(readme.contains("docs/cavenic-spider-blindness-on-hit-mvp.md"));
        assertTrue(readme.contains("fourth direct Cavenic mob foundation"));
        assertTrue(readme.contains("bounded CAVERN-only natural spawning"));
        assertTrue(readme.contains("vanilla spider loot baseline"));
        assertTrue(readme.contains("legacy `1/8` `cavenic_orb` drop"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity"));
        assertTrue(readme.contains("legacy difficulty-scaled blindness-on-hit behavior"));
        assertTrue(readme.contains("Cavenic Witch Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-natural-spawn-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Legacy Loot MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-loot-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-damage-behavior-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Same-Type Projectile Immunity MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-projectile-immunity-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Friendship Targeting MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-friendship-targeting-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Custom Ranged Potion MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-ranged-potion-mvp.md"));
        assertTrue(readme.contains("docs/cavenic-witch-magic-book-deferred.md"));
        assertTrue(readme.contains("fifth direct Cavenic mob foundation"));
        assertTrue(readme.contains("bounded CAVERN-only natural spawning"));
        assertTrue(readme.contains("vanilla witch loot baseline"));
        assertTrue(readme.contains("legacy `1/5` `cavenic_orb` drop appended on top of the vanilla witch loot baseline"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity behavior"));
        assertTrue(readme.contains("legacy same-type/self source-immunity behavior"));
        assertTrue(readme.contains("legacy same-type friendship-target rejection behavior"));
        assertTrue(readme.contains("restored legacy ranged-potion behavior for normal combat targets"));
        assertTrue(readme.contains("the modern non-witch Raider-heal branch remains an intentional bounded bridge"));
        assertTrue(readme.contains("the inspected legacy magic-book branch remains explicitly deferred because `ItemMagicBook` is still a broader subtype/NBT/capability spellbook system"));
        assertTrue(readme.contains("Cavenic Bear Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Bear Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-natural-spawn-mvp.md"));
        assertTrue(readme.contains("docs/cavenic-bear-loot-absent-or-deferred.md"));
        assertTrue(readme.contains("Cavenic Bear Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-damage-behavior-mvp.md"));
        assertTrue(readme.contains("Cavenic Bear Legacy Hostile Targeting MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-hostile-targeting-mvp.md"));
        assertTrue(readme.contains("Cavenic Bear Legacy Melee Attack MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-melee-attack-mvp.md"));
        assertTrue(readme.contains("Cavenic Bear Legacy Panic Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-panic-behavior-mvp.md"));
        assertTrue(readme.contains("Cavenic Bear Passive / Movement AI Boundary MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-passive-ai-equivalent-or-deferred.md"));
        assertTrue(readme.contains("sixth direct Cavenic mob foundation"));
        assertTrue(readme.contains("legacy texture on the vanilla polar bear renderer path"));
        assertTrue(readme.contains("vanilla polar bear loot baseline"));
        assertTrue(readme.contains("bounded CAVERN-only natural spawning"));
        assertTrue(readme.contains("the inspected legacy bear loot line remains explicitly absent because `EntityCavenicBear` never overrides `dropLoot(...)`"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity behavior"));
        assertTrue(readme.contains("bounded legacy player-target / hurt-by-target hostility slice"));
        assertTrue(readme.contains("bounded legacy melee-attack behavior"));
        assertTrue(readme.contains("bounded legacy panic behavior"));
        assertTrue(readme.contains("the remaining passive/movement bear goals stay on the inherited modern polar bear base"));
        assertTrue(readme.contains("Crazy Zombie Baseline MVP"));
        assertTrue(readme.contains("docs/crazy-zombie-baseline-mvp.md"));
        assertTrue(readme.contains("docs/crazy-zombie-loot-mvp.md"));
        assertTrue(readme.contains("docs/crazy-zombie-damage-behavior-mvp.md"));
        assertTrue(readme.contains("docs/crazy-zombie-boss-bar-mvp.md"));
        assertTrue(readme.contains("docs/crazy-zombie-particle-trail-mvp.md"));
        assertTrue(readme.contains("docs/crazy-zombie-natural-spawn-absent-or-deferred.md"));
        assertTrue(readme.contains("first legacy crazy-variant foundation follow-up"));
        assertTrue(readme.contains("`crazy_zombie`"));
        assertTrue(readme.contains("inherited legacy `1/8` `cavenic_orb` drop appended on top of the vanilla zombie loot baseline"));
        assertTrue(readme.contains("inherited legacy fall-damage reduction and fire-damage immunity behavior"));
        assertTrue(readme.contains("legacy blue progress boss bar and sky-darkening boss-event branch"));
        assertTrue(readme.contains("legacy client-only portal-tinted particle trail"));
        assertTrue(readme.contains("Cavenia-only crazy-roster provider/config branch"));
        assertTrue(readme.contains("Crazy Skeleton Baseline MVP"));
        assertTrue(readme.contains("docs/crazy-skeleton-baseline-mvp.md"));
        assertTrue(readme.contains("second crazy-variant foundation follow-up"));
        assertTrue(readme.contains("`crazy_skeleton`"));
        assertTrue(readme.contains("vanilla skeleton loot baseline"));
        assertTrue(readme.contains("docs/crazy-skeleton-loot-mvp.md"));
        assertTrue(readme.contains("docs/crazy-skeleton-damage-behavior-mvp.md"));
        assertTrue(readme.contains("docs/crazy-skeleton-boss-bar-mvp.md"));
        assertTrue(readme.contains("inherited legacy `1/5` `cavenic_orb` drop is now restored explicitly on top of that same vanilla skeleton loot baseline"));
        assertTrue(readme.contains("inherited legacy fall-damage reduction and fire-damage immunity behavior are now restored explicitly on top of that same vanilla skeleton baseline"));
        assertTrue(readme.contains("legacy white progress boss bar and sky-darkening boss-event branch are now restored explicitly on top of that same vanilla skeleton baseline"));
        assertTrue(readme.contains("legacy `EntityAIAttackCavenicBow` path"));
        assertTrue(readme.contains("docs/crazy-skeleton-cavenic-bow-equipment-mvp.md"));
        assertTrue(readme.contains("docs/crazy-skeleton-ranged-ai-mvp.md"));
        assertTrue(readme.contains("guaranteed `Cavenic Bow` mainhand, forced `Infinity` enchantment and `1.0F` mainhand drop chance are now restored explicitly"));
        assertTrue(readme.contains("legacy `EntityAIAttackCavenicBow` path is now restored explicitly through a local Crazy Skeleton-only goal swap"));
        assertTrue(readme.contains("Crazy Creeper Baseline MVP"));
        assertTrue(readme.contains("docs/crazy-creeper-baseline-mvp.md"));
        assertTrue(readme.contains("docs/crazy-creeper-loot-mvp.md"));
        assertTrue(readme.contains("docs/crazy-creeper-damage-behavior-mvp.md"));
        assertTrue(readme.contains("docs/crazy-creeper-boss-bar-mvp.md"));
        assertTrue(readme.contains("docs/crazy-creeper-particle-trail-mvp.md"));
        assertTrue(readme.contains("docs/crazy-creeper-fuse-explosion-mvp.md"));
        assertTrue(readme.contains("docs/crazy-creeper-lightning-charged-swelling-boundary.md"));
        assertTrue(readme.contains("third crazy-variant foundation follow-up"));
        assertTrue(readme.contains("`crazy_creeper`"));
        assertTrue(readme.contains("vanilla creeper loot baseline"));
        assertTrue(readme.contains("inherited legacy `1/5` `cavenic_orb` drop is now restored explicitly on top of that same vanilla creeper loot baseline"));
        assertTrue(readme.contains("inherited legacy fall-damage reduction and fire-damage immunity behavior are now restored explicitly on top of that same vanilla creeper baseline"));
        assertTrue(readme.contains("legacy green progress boss bar and sky-darkening boss-event branch are now restored explicitly on top of that same vanilla creeper baseline"));
        assertTrue(readme.contains("legacy client-only portal-tinted particle trail is now restored explicitly on top of that same vanilla creeper baseline through the shared `crazy_mob` particle mapping"));
        assertTrue(readme.contains("fixed legacy `Fuse = 150` / `ExplosionRadius = 30` values are now restored explicitly through the modern creeper save-data path"));
        assertTrue(readme.contains("inspected legacy lightning/charged/swelling branch is now pinned as inherited vanilla creeper behavior"));
        assertTrue(readme.contains("Crazy Spider Baseline MVP"));
        assertTrue(readme.contains("docs/crazy-spider-baseline-mvp.md"));
        assertTrue(readme.contains("docs/crazy-spider-loot-mvp.md"));
        assertTrue(readme.contains("docs/crazy-spider-damage-behavior-mvp.md"));
        assertTrue(readme.contains("docs/crazy-spider-boss-bar-mvp.md"));
        assertTrue(readme.contains("docs/crazy-spider-particle-trail-mvp.md"));
        assertTrue(readme.contains("docs/crazy-spider-combat-effects-mvp.md"));
        assertTrue(readme.contains("Cavenia Crazy Roster Natural Spawn Boundary MVP"));
        assertTrue(readme.contains("docs/cavenia-crazy-roster-natural-spawn-boundary.md"));
        assertTrue(readme.contains("Cavenia Dimension / Provider Foundation Boundary"));
        assertTrue(readme.contains("docs/cavenia-dimension-provider-foundation-boundary.md"));
        assertTrue(readme.contains("Cavenia Dimension Key / Type Contract Boundary"));
        assertTrue(readme.contains("docs/cavenia-dimension-key-type-contract-boundary.md"));
        assertTrue(readme.contains("Cavenia Biome Provider / Biome List Contract Boundary"));
        assertTrue(readme.contains("docs/cavenia-biome-provider-contract-boundary.md"));
        assertTrue(readme.contains("Cavenia VEINS / Content Pipeline Contract Boundary"));
        assertTrue(readme.contains("docs/cavenia-veins-content-pipeline-contract-boundary.md"));
        assertTrue(readme.contains("Cavenia Chunk Generator / Terrain Pipeline Contract Boundary"));
        assertTrue(readme.contains("docs/cavenia-chunk-generator-terrain-pipeline-contract-boundary.md"));
        assertTrue(readme.contains("Cavenia Cave Carver / MapGenCaveniaCaves Contract Boundary"));
        assertTrue(readme.contains("docs/cavenia-cave-carver-mapgen-contract-boundary.md"));
        assertTrue(readme.contains("Cavenia Population / Lakes / Falls / Cavenic Shroom Contract Boundary"));
        assertTrue(readme.contains("docs/cavenia-population-lakes-falls-shroom-contract-boundary.md"));
        assertTrue(readme.contains("Cavenia Mirage Entry / Access Path Contract Boundary"));
        assertTrue(readme.contains("docs/cavenia-mirage-entry-access-contract-boundary.md"));
        assertTrue(readme.contains("Cavenia Spawn Provider / Crazy Roster Activation Contract Boundary"));
        assertTrue(readme.contains("docs/cavenia-spawn-provider-crazy-roster-activation-contract-boundary.md"));
        assertTrue(readme.contains("Cavenia Spawn Provider Policy / Non-Runtime MVP"));
        assertTrue(readme.contains("docs/cavenia-spawn-provider-policy-mvp.md"));
        assertTrue(readme.contains("Caveman Baseline / Cavenia Normal Spawn Roster Boundary"));
        assertTrue(readme.contains("docs/caveman-cavenia-normal-roster-boundary.md"));
        assertTrue(readme.contains("Cavenia Active Foundation Readiness / Implementation Plan"));
        assertTrue(readme.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(readme.contains("Cavenia Active Foundation Technical Spike"));
        assertTrue(readme.contains("docs/cavenia-active-foundation-technical-spike.md"));
        assertTrue(readme.contains("Cavenia Runtime Key / Inactive Dimension Scaffold MVP"));
        assertTrue(readme.contains("docs/cavenia-runtime-key-inactive-dimension-scaffold-mvp.md"));
        assertTrue(readme.contains("Cavenia Terrain Generator Foundation / Non-Runtime MVP"));
        assertTrue(readme.contains("docs/cavenia-terrain-generator-foundation-non-runtime-mvp.md"));
        assertTrue(readme.contains("Cavenia Biome Top/Filter Policy / Non-Runtime MVP"));
        assertTrue(readme.contains("docs/cavenia-biome-top-filter-policy-non-runtime-mvp.md"));
        assertTrue(readme.contains("Cavenia VEINS / Content Policy / Non-Runtime MVP"));
        assertTrue(readme.contains("docs/cavenia-veins-content-policy-non-runtime-mvp.md"));
        assertTrue(readme.contains("Cavenia Population Policy / Non-Runtime MVP"));
        assertTrue(readme.contains("docs/cavenia-population-policy-non-runtime-mvp.md"));
        assertTrue(readme.contains("Cavenia Active Generator Technical Scaffold / MVP"));
        assertTrue(readme.contains("docs/cavenia-active-generator-technical-scaffold-mvp.md"));
        assertTrue(readme.contains("Cavenia Active Generator Runtime Prototype / Inert App-Side Bridge MVP"));
        assertTrue(readme.contains("docs/cavenia-active-generator-runtime-prototype-inert-bridge-mvp.md"));
        assertTrue(readme.contains("Cavenia Active Generator Registration / Inert Activation Boundary MVP"));
        assertTrue(readme.contains("docs/cavenia-active-generator-registration-inert-boundary-mvp.md"));
        assertTrue(readme.contains("Cavenia Chunk Generator / Biome Source Unregistered Skeleton MVP"));
        assertTrue(readme.contains("docs/cavenia-generator-biome-source-unregistered-skeleton-mvp.md"));
        assertTrue(readme.contains("Cavenia Generator Runtime Contract Interfaces / Non-Registered MVP"));
        assertTrue(readme.contains("docs/cavenia-generator-runtime-contracts-non-registered-mvp.md"));
        assertTrue(readme.contains("Cavenia Generator Activation-Readiness Runtime Host Contracts MVP"));
        assertTrue(readme.contains("docs/cavenia-generator-activation-readiness-host-contracts-mvp.md"));
        assertTrue(readme.contains("Cavenia Generator Host / Biome Source Strategy Host Split Contracts MVP"));
        assertTrue(readme.contains("docs/cavenia-generator-host-biome-source-strategy-split-contracts-mvp.md"));
        assertTrue(readme.contains("Cavenia Runtime BiomeSource First Implementation Decision / Guardrails MVP"));
        assertTrue(readme.contains("docs/cavenia-runtime-biome-source-first-implementation-decision-guardrails-mvp.md"));
        assertTrue(readme.contains("Cavenia Guarded Unregistered Real BiomeSource Subclass Stub MVP"));
        assertTrue(readme.contains("Cavenia Runtime BiomeSource Holder/Resource-Key Conversion Readiness MVP"));
        assertTrue(readme.contains("Cavenia Runtime BiomeSource Fallback Policy Readiness MVP"));
        assertTrue(readme.contains("docs/cavenia-runtime-biome-source-holder-resource-key-conversion-readiness-mvp.md"));
        assertTrue(readme.contains("docs/cavenia-runtime-biome-source-fallback-policy-readiness-mvp.md"));
        assertTrue(readme.contains("docs/cavenia-guarded-unregistered-real-biome-source-subclass-stub-mvp.md"));
        assertTrue(readme.contains("full mirage-world stack"));
        assertTrue(readme.contains("old Cavenia-only `crazySpawnChance` plus a nearby `ICavenicMob` scan for `!entity.isNonBoss()`"));
        assertTrue(readme.contains("fourth crazy-variant foundation follow-up"));
        assertTrue(readme.contains("`crazy_spider`"));
        assertTrue(readme.contains("vanilla spider loot baseline"));
        assertTrue(readme.contains("inherited legacy `1/8` `cavenic_orb` drop is now restored explicitly on top of that same vanilla spider loot baseline"));
        assertTrue(readme.contains("inherited legacy fall-damage reduction and fire-damage immunity behavior are now restored explicitly on top of that same vanilla spider baseline"));
        assertTrue(readme.contains("legacy successful-hit blindness/poison combat branch is now restored explicitly on top of that same vanilla spider baseline"));
        assertTrue(readme.contains("legacy red progress boss bar and sky-darkening boss-event branch are now restored explicitly on top of that same vanilla spider baseline"));
        assertTrue(readme.contains("legacy client-only portal-tinted particle trail is now restored explicitly on top of that same vanilla spider baseline through the shared `crazy_mob` particle mapping"));
        assertTrue(readme.contains("vanilla zombie loot baseline"));
    }

    @Test
    void runtimeSmokeDocCoversCommandsAndScope() throws IOException {
        String doc = Files.readString(RUNTIME_SMOKE);

        assertTrue(doc.contains("NeoForge GameTest runtime smoke"));
        assertTrue(doc.contains("runtime registry availability for tranche 2 content"));
        assertTrue(doc.contains("acresia runtime registry ids"));
        assertTrue(doc.contains("acresia seed planting smoke"));
        assertTrue(doc.contains("acresia mature normal harvest smoke"));
        assertTrue(doc.contains("acresia shear-harvest regrowth smoke"));
        assertTrue(doc.contains("acresia edible fruit wiring"));
        assertTrue(doc.contains("acresia worldgen configured/placed key resolution"));
        assertTrue(doc.contains("cavenic shroom runtime registry ids"));
        assertTrue(doc.contains("cavenic shroom bounded collision nausea"));
        assertTrue(doc.contains("cavenic shroom bounded shear-harvest helper wiring"));
        assertTrue(doc.contains("cavenic orb drop policy/runtime smoke"));
        assertTrue(doc.contains("cavenic bow runtime registry id"));
        assertTrue(doc.contains("cavenic bow max-damage and damageable-item smoke"));
        assertTrue(doc.contains("cavenic bow repairability with `cavernreborn:cavenic_orb`"));
        assertTrue(doc.contains("cavenic bow no-repair-with-stick smoke"));
        assertTrue(doc.contains("cavenic bow default mode/runtime stack-state smoke"));
        assertTrue(doc.contains("cavenic bow mode cycling order and persistence"));
        assertTrue(doc.contains("cavenic bow sneak-use mode-cycling smoke"));
        assertTrue(doc.contains("cavenic bow RAPID adjusted-shot-power smoke"));
        assertTrue(doc.contains("cavenic bow RAPID higher-velocity vanilla-arrow smoke"));
        assertTrue(doc.contains("cavenic bow RAPID no-extra-durability smoke"));
        assertTrue(doc.contains("cavenic bow RAPID still spawning a vanilla arrow entity"));
        assertTrue(doc.contains("cavenic bow RAPID low-armor hurt-resistance reset smoke"));
        assertTrue(doc.contains("cavenic bow RAPID armored-target no-reset smoke"));
        assertTrue(doc.contains("cavenic bow RAPID not inheriting the SNIPE damage multiplier"));
        assertTrue(doc.contains("cavenic bow full-charge SNIPE projectile boost smoke"));
        assertTrue(doc.contains("cavenic bow full-charge SNIPE extra-durability smoke"));
        assertTrue(doc.contains("cavenic bow full-charge SNIPE still spawning a vanilla arrow entity"));
        assertTrue(doc.contains("cavenic bow TORCH vanilla-arrow marker smoke"));
        assertTrue(doc.contains("cavenic bow TORCH valid block-placement smoke"));
        assertTrue(doc.contains("cavenic bow TORCH invalid-target no-placement smoke"));
        assertTrue(doc.contains("cavenic bow TORCH torch-consumption smoke"));
        assertTrue(doc.contains("cavenic bow TORCH wall-torch orientation smoke"));
        assertTrue(doc.contains("cavenic bow TORCH no-custom-entity smoke"));
        assertTrue(doc.contains("cavenic bow TORCH item-use-forwarding boundary smoke"));
        assertTrue(doc.contains("cavenic bow TORCH not inheriting RAPID or SNIPE behavior"));
        assertTrue(doc.contains("entity cavenic arrow projectile boundary smoke"));
        assertTrue(doc.contains("rapid/torch arrow projectile boundary smoke"));
        assertTrue(doc.contains("cavenic zombie runtime registry id"));
        assertTrue(doc.contains("cavenic zombie attribute registration smoke"));
        assertTrue(doc.contains("cavenic zombie hostile runtime spawn smoke"));
        assertTrue(doc.contains("cavenic zombie spawn egg resolution"));
        assertTrue(doc.contains("cavenic zombie spawn egg entity-creation smoke"));
        assertTrue(doc.contains("cavenic zombie natural spawn placement registration"));
        assertTrue(doc.contains("cavenic zombie CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("cavenic zombie biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic zombie biome tag resolution"));
        assertTrue(doc.contains("cavenic zombie vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic zombie legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("cavenic zombie legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("cavenic zombie legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic zombie legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic zombie generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic skeleton runtime registry id"));
        assertTrue(doc.contains("cavenic skeleton attribute registration smoke"));
        assertTrue(doc.contains("cavenic skeleton hostile runtime spawn smoke"));
        assertTrue(doc.contains("cavenic skeleton spawn egg resolution"));
        assertTrue(doc.contains("cavenic skeleton spawn egg entity-creation smoke"));
        assertTrue(doc.contains("cavenic skeleton natural spawn placement registration"));
        assertTrue(doc.contains("cavenic skeleton CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("cavenic skeleton biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic skeleton biome tag resolution"));
        assertTrue(doc.contains("cavenic skeleton vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic skeleton legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("cavenic skeleton legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("cavenic skeleton legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic skeleton legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic skeleton generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic creeper runtime registry id"));
        assertTrue(doc.contains("cavenic creeper attribute registration smoke"));
        assertTrue(doc.contains("cavenic creeper hostile runtime spawn smoke"));
        assertTrue(doc.contains("cavenic creeper vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic creeper spawn egg resolution"));
        assertTrue(doc.contains("cavenic creeper spawn egg entity-creation smoke"));
        assertTrue(doc.contains("cavenic creeper natural spawn placement registration"));
        assertTrue(doc.contains("cavenic creeper CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("cavenic creeper biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic creeper biome tag resolution"));
        assertTrue(doc.contains("cavenic creeper legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("cavenic creeper legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("cavenic creeper legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic creeper legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic creeper generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic creeper legacy fuse-time smoke"));
        assertTrue(doc.contains("cavenic creeper legacy explosion-radius smoke"));
        assertTrue(doc.contains("crazy creeper runtime registry id"));
        assertTrue(doc.contains("crazy creeper attribute registration"));
        assertTrue(doc.contains("crazy creeper hostile runtime spawn"));
        assertTrue(doc.contains("crazy creeper spawn egg resolution"));
        assertTrue(doc.contains("crazy creeper spawn egg entity creation"));
        assertTrue(doc.contains("crazy creeper vanilla creeper loot-table baseline"));
        assertTrue(doc.contains("crazy creeper legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("crazy creeper legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("crazy creeper legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("crazy creeper legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("crazy creeper generic-damage baseline smoke"));
        assertTrue(doc.contains("crazy creeper boss-event wiring smoke"));
        assertTrue(doc.contains("crazy creeper boss-bar color/overlay smoke"));
        assertTrue(doc.contains("non-runtime Cavenia spawn-provider policy constant and roster smoke"));
        assertTrue(doc.contains("crazy creeper boss-percent update smoke"));
        assertTrue(doc.contains("crazy creeper tracked-player add/remove smoke"));
        assertTrue(doc.contains("crazy creeper sky-darkening smoke"));
        assertTrue(doc.contains("crazy creeper particle type registry id smoke"));
        assertTrue(doc.contains("crazy creeper particle provider registration source smoke"));
        assertTrue(doc.contains("crazy creeper particle description resource smoke"));
        assertTrue(doc.contains("crazy creeper client-only particle spawn-source smoke"));
        assertTrue(doc.contains("crazy creeper legacy fuse-time smoke"));
        assertTrue(doc.contains("crazy creeper legacy explosion-radius smoke"));
        assertTrue(doc.contains("crazy creeper fuse/explosion save-data round-trip smoke"));
        assertTrue(doc.contains("crazy creeper explicit no-natural-spawn baseline boundary"));
        assertTrue(doc.contains("crazy creeper inherited-vanilla lightning/charged/swelling boundary smoke"));
        assertTrue(doc.contains("actual client visual crazy creeper particle feel remains manual"));
        assertTrue(doc.contains("actual Crazy Creeper destructive explosion gameplay feel remains manual"));
        assertTrue(doc.contains("crazy spider runtime registry id"));
        assertTrue(doc.contains("crazy spider attribute registration"));
        assertTrue(doc.contains("crazy spider hostile runtime spawn"));
        assertTrue(doc.contains("crazy spider spawn egg resolution"));
        assertTrue(doc.contains("crazy spider spawn egg entity creation"));
        assertTrue(doc.contains("crazy spider vanilla spider loot-table baseline"));
        assertTrue(doc.contains("crazy spider legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("crazy spider legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("crazy spider legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("crazy spider legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("crazy spider generic-damage baseline smoke"));
        assertTrue(doc.contains("crazy spider boss-event wiring smoke"));
        assertTrue(doc.contains("crazy spider boss-bar color/overlay smoke"));
        assertTrue(doc.contains("crazy spider boss-percent update smoke"));
        assertTrue(doc.contains("crazy spider tracked-player add/remove smoke"));
        assertTrue(doc.contains("crazy spider sky-darkening smoke"));
        assertTrue(doc.contains("crazy spider successful-hit blindness/poison runtime smoke"));
        assertTrue(doc.contains("crazy spider exact difficulty-duration mapping smoke"));
        assertTrue(doc.contains("crazy spider existing-effect skip smoke"));
        assertTrue(doc.contains("vanilla spider no-blindness/no-poison comparison smoke"));
        assertTrue(doc.contains("consolidated crazy-mob natural-spawn deferral smoke through the inspected Cavenia-only roster/provider path"));
        assertTrue(doc.contains("crazy zombie, crazy skeleton, crazy creeper and crazy spider spawn placement unregistered smoke"));
        assertTrue(doc.contains("crazy zombie, crazy skeleton, crazy creeper and crazy spider no-normal-`CAVERN` biome-modifier smoke"));
        assertTrue(doc.contains("crazy zombie, crazy skeleton, crazy creeper and crazy spider no-normal-`CAVERN` spawn-biome-tag smoke"));
        assertTrue(doc.contains("crazy spider explicit no-natural-spawn baseline boundary"));
        assertTrue(doc.contains("actual long-run crazy spider orb drop-rate balance is not covered by server GameTests"));
        assertTrue(doc.contains("actual long-running Crazy Spider fire/lava gameplay feel remains manual"));
        assertTrue(doc.contains("actual client visual crazy spider boss-bar feel remains manual"));
        assertTrue(doc.contains("cavenic spider runtime registry id"));
        assertTrue(doc.contains("cavenic spider attribute registration smoke"));
        assertTrue(doc.contains("cavenic spider hostile runtime spawn smoke"));
        assertTrue(doc.contains("cavenic spider vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic spider spawn egg resolution"));
        assertTrue(doc.contains("cavenic spider spawn egg entity-creation smoke"));
        assertTrue(doc.contains("cavenic spider natural spawn placement registration"));
        assertTrue(doc.contains("cavenic spider CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("cavenic spider biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic spider biome tag resolution"));
        assertTrue(doc.contains("cavenic spider legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("cavenic spider legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("cavenic spider legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic spider legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic spider generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic spider blindness-on-hit runtime smoke"));
        assertTrue(doc.contains("vanilla spider no-blindness comparison smoke"));
        assertTrue(doc.contains("cavenic witch runtime registry id"));
        assertTrue(doc.contains("cavenic witch attribute registration smoke"));
        assertTrue(doc.contains("cavenic witch hostile runtime spawn smoke"));
        assertTrue(doc.contains("cavenic witch vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic witch spawn egg resolution"));
        assertTrue(doc.contains("cavenic witch spawn egg entity-creation smoke"));
        assertTrue(doc.contains("cavenic witch natural spawn placement registration"));
        assertTrue(doc.contains("cavenic witch CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("cavenic witch biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic witch biome tag resolution"));
        assertTrue(doc.contains("cavenic witch legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("cavenic witch deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("cavenic witch legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic witch legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic witch generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic witch legacy same-type/self source-immunity smoke"));
        assertTrue(doc.contains("cavenic witch non-immune source baseline smoke"));
        assertTrue(doc.contains("cavenic witch same-type friendship target rejection smoke"));
        assertTrue(doc.contains("cavenic witch non-friend target baseline smoke"));
        assertTrue(doc.contains("legacy cavenic witch magic-book branch because the inspected legacy `ItemMagicBook` depends on subtype, NBT, capability and spellbook systems that Reborn does not yet implement honestly"));
        assertTrue(doc.contains("cavenic bow enchantment applicability"));
        assertTrue(doc.contains("cavenic bow cavenic item tag resolution"));
        assertTrue(doc.contains("cavenic bow recipe manager resolution"));
        assertTrue(doc.contains("cavenic shroom worldgen configured/placed key resolution"));
        assertTrue(doc.contains("aquamarine tool runtime registry ids"));
        assertTrue(doc.contains("aquamarine tool repairability with `cavernreborn:aquamarine`"));
        assertTrue(doc.contains("aquamarine tool enchantment applicability"));
        assertTrue(doc.contains("aquamarine underwater utility policy/runtime smoke"));
        assertTrue(doc.contains("magnite tool runtime registry ids"));
        assertTrue(doc.contains("magnite tool repairability with `cavernreborn:magnite_ingot`"));
        assertTrue(doc.contains("magnite tool enchantment applicability"));
        assertTrue(doc.contains("magnite brittle max-damage/runtime smoke"));
        assertTrue(doc.contains("magnite no-unintended-Mining-Assist runtime smoke"));
        assertTrue(doc.contains("magnite armor runtime registry ids"));
        assertTrue(doc.contains("magnite armor repairability with `cavernreborn:magnite_ingot`"));
        assertTrue(doc.contains("magnite armor enchantment applicability"));
        assertTrue(doc.contains("magnite armor durability and slot/equippable runtime behavior"));
        assertTrue(doc.contains("hexcite normal and Silk Touch loot paths"));
        assertTrue(doc.contains("randomite curated runtime loot output"));
        assertTrue(doc.contains("hexcite pickaxe enchantment applicability"));
        assertTrue(doc.contains("hexcite armor runtime registry ids"));
        assertTrue(doc.contains("hexcite armor repairability with `cavernreborn:hexcite`"));
        assertTrue(doc.contains("hexcite armor durability and slot/equippable runtime behavior"));
        assertTrue(doc.contains("hexcite armor enchantment applicability"));
        assertTrue(doc.contains("miner_orb runtime registry availability"));
        assertTrue(doc.contains("randomite allowed-drop runtime coverage that now includes miner_orb in the curated pool"));
        assertTrue(doc.contains("miner_orb bonus policy/runtime smoke"));
        assertTrue(doc.contains("ore_compass runtime registry availability"));
        assertTrue(doc.contains("ore_compass target tag resolution"));
        assertTrue(doc.contains("ore_compass scanner nearest-target behavior"));
        assertTrue(doc.contains("ore_compass stored-target state round-trip"));
        assertTrue(doc.contains("ore_compass tracking policy/runtime ids"));
        assertTrue(doc.contains("unsupported/fissured/storage exclusion during ore_compass scans"));
        assertTrue(doc.contains("Mining Assist policy/runtime ids"));
        assertTrue(doc.contains("bounded same-block vein assist with hexcite_pickaxe"));
        assertTrue(doc.contains("no unlock means no assist"));
        assertTrue(doc.contains("sneaking disables assist"));
        assertTrue(doc.contains("fissured_stone exclusion"));
        assertTrue(doc.contains("fissured stone no-drop behavior"));
        assertTrue(doc.contains("fissured stone survival effect behavior"));
        assertTrue(doc.contains("fissured stone creative guard"));
        assertTrue(doc.contains("fissured stone non-destructive behavior"));
        assertTrue(doc.contains("progression policy ids/scores"));
        assertTrue(doc.contains("worldgen configured/placed feature runtime resolution"));
        assertTrue(doc.contains("./gradlew --no-daemon :app-neoforge:runGameTestServer"));
        assertTrue(doc.contains("docker compose run --rm gradle ./gradlew --no-daemon :app-neoforge:runGameTestServer"));
        assertTrue(doc.contains("scripts/runtime-smoke.sh"));
        assertTrue(doc.contains("minecraft:empty"));
        assertTrue(doc.contains("app-neoforge/src/gameteststructures/empty.snbt"));
        assertTrue(doc.contains("GameTestRegistry.register(CavernSpecialOreGameTests.class)"));
        assertTrue(doc.contains("unguarded `GameTestRegistry.register"));
        assertTrue(doc.contains("GameTestHooks.isGametestEnabled()"));
        assertTrue(doc.contains("infrastructure workaround"));
        assertTrue(doc.contains("does not change gameplay behavior"));
        assertTrue(doc.contains("manual client smoke is still needed"));
        assertTrue(doc.contains("actual client-visible needle feel still requires manual smoke"));
        assertTrue(doc.contains("actual worn hexcite armor appearance"));
        assertTrue(doc.contains("actual worn magnite armor appearance"));
        assertTrue(doc.contains("actual Acresia in-world farming feel and growth cadence"));
        assertTrue(doc.contains("actual Cavenic Shroom hazard feel, sparse spread feel and harvest feel"));
        assertTrue(doc.contains("actual Cavenic Bow draw, release and visual client feel"));
        assertTrue(doc.contains("actual Cavenic Zombie renderer/model visual feel"));
        assertTrue(doc.contains("actual Cavenic Skeleton renderer/model visual feel"));
        assertTrue(doc.contains("actual Cavenic Creeper renderer/model visual feel"));
        assertTrue(doc.contains("actual Cavenic Spider renderer/model visual feel"));
        assertTrue(doc.contains("actual Cavenic Witch renderer/model visual feel"));
        assertTrue(doc.contains("actual long-run cavenic spider orb-drop rate balance"));
        assertTrue(doc.contains("actual long-running Cavenic Spider fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-running Cavenic Spider combat/pathfinding feel"));
        assertTrue(doc.contains("actual poison/web-based Cavenic Spider gameplay behavior"));
        assertTrue(doc.contains("actual Cavenic Witch combat, potion-throw and pathfinding feel"));
        assertTrue(doc.contains("cavenic witch legacy ranged-potion runtime smoke"));
        assertTrue(doc.contains("cavenic witch deterministic legacy potion-selection smoke"));
        assertTrue(doc.contains("cavenic witch explicit high-health and low-health potion-threshold smoke"));
        assertTrue(doc.contains("cavenic witch explicit weakness/slowness/harming fallback smoke"));
        assertTrue(doc.contains("cavenic witch deterministic legacy thrown-potion construction smoke"));
        assertTrue(doc.contains("cavenic witch direct non-friend ranged-attack branch smoke"));
        assertTrue(doc.contains("cavenic witch preserved non-witch Raider bridge smoke"));
        assertTrue(doc.contains("cavenic bear runtime registry id"));
        assertTrue(doc.contains("cavenic bear attribute registration smoke"));
        assertTrue(doc.contains("cavenic bear runtime entity spawn smoke"));
        assertTrue(doc.contains("cavenic bear vanilla polar bear loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic bear explicit no-custom-loot boundary from the inspected legacy source"));
        assertTrue(doc.contains("cavenic bear spawn egg resolution"));
        assertTrue(doc.contains("cavenic bear spawn egg entity-creation smoke"));
        assertTrue(doc.contains("crazy zombie runtime registry id"));
        assertTrue(doc.contains("crazy zombie attribute registration smoke"));
        assertTrue(doc.contains("`generic.max_health` clamp"));
        assertTrue(doc.contains("crazy zombie hostile runtime spawn smoke"));
        assertTrue(doc.contains("crazy zombie spawn egg resolution"));
        assertTrue(doc.contains("crazy zombie spawn egg entity-creation smoke"));
        assertTrue(doc.contains("crazy zombie vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("crazy zombie legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("crazy zombie legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("crazy zombie legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("crazy zombie legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("crazy zombie generic-damage baseline smoke"));
        assertTrue(doc.contains("crazy zombie legacy knockback-on-hit melee smoke"));
        assertTrue(doc.contains("crazy zombie deterministic legacy knockback helper smoke"));
        assertTrue(doc.contains("crazy zombie boss-event wiring smoke"));
        assertTrue(doc.contains("crazy zombie boss-bar color/overlay smoke"));
        assertTrue(doc.contains("crazy zombie boss-percent update smoke"));
        assertTrue(doc.contains("crazy zombie tracked-player add/remove smoke"));
        assertTrue(doc.contains("crazy zombie sky-darkening smoke"));
        assertTrue(doc.contains("crazy zombie particle type registry id smoke"));
        assertTrue(doc.contains("crazy zombie particle provider registration source smoke"));
        assertTrue(doc.contains("crazy zombie particle description resource smoke"));
        assertTrue(doc.contains("crazy zombie client-only particle spawn-source smoke"));
        assertTrue(doc.contains("explicit Crazy Zombie natural-spawn deferred boundary"));
        assertTrue(doc.contains("Cavenia-only crazy-roster provider/config path"));
        assertTrue(doc.contains("crazy skeleton runtime registry id"));
        assertTrue(doc.contains("crazy skeleton attribute registration"));
        assertTrue(doc.contains("crazy skeleton hostile runtime spawn"));
        assertTrue(doc.contains("crazy skeleton spawn egg resolution"));
        assertTrue(doc.contains("crazy skeleton spawn egg entity creation"));
        assertTrue(doc.contains("crazy skeleton vanilla skeleton loot-table baseline"));
        assertTrue(doc.contains("crazy skeleton guaranteed cavenic bow equipment smoke"));
        assertTrue(doc.contains("crazy skeleton Infinity enchantment smoke"));
        assertTrue(doc.contains("crazy skeleton mainhand drop chance smoke"));
        assertTrue(doc.contains("crazy skeleton legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("crazy skeleton legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("crazy skeleton legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("crazy skeleton legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("crazy skeleton generic-damage baseline smoke"));
        assertTrue(doc.contains("crazy skeleton boss-event wiring smoke"));
        assertTrue(doc.contains("crazy skeleton boss-bar color/overlay smoke"));
        assertTrue(doc.contains("crazy skeleton boss-percent update smoke"));
        assertTrue(doc.contains("crazy skeleton tracked-player add/remove smoke"));
        assertTrue(doc.contains("crazy skeleton sky-darkening smoke"));
        assertTrue(doc.contains("crazy skeleton explicit no-natural-spawn baseline boundary"));
        assertTrue(doc.contains("crazy skeleton continued vanilla attack-damage baseline, explicit `1024.0` max-health clamp and guaranteed `Cavenic Bow` + `Infinity` equipment stability smoke"));
        assertTrue(doc.contains("crazy skeleton legacy cavenic bow ranged-goal wiring smoke"));
        assertTrue(doc.contains("crazy skeleton legacy ranged-goal constants smoke"));
        assertTrue(doc.contains("crazy skeleton local melee fallback switch smoke"));
        assertTrue(doc.contains("crazy skeleton vanilla and cavenic skeleton no-global-ai-change smoke"));
        assertTrue(doc.contains("actual client-visible Crazy Creeper boss-bar feel remains manual"));
        assertFalse(doc.contains("crazy creeper particle trail remains out of scope"));
        assertTrue(doc.contains("actual client-visible Crazy Skeleton boss-bar feel remains manual"));
        assertTrue(doc.contains("actual Crazy Zombie client boss-bar visual feel"));
        assertTrue(doc.contains("actual Crazy Zombie client particle-trail visual feel"));
        assertTrue(doc.contains("actual long-running Crazy Zombie melee-knockback feel beyond the deterministic helper/runtime smoke"));
        assertTrue(doc.contains("crazy spider particle type registry id smoke"));
        assertTrue(doc.contains("crazy spider particle provider registration source smoke"));
        assertTrue(doc.contains("crazy spider particle description resource smoke"));
        assertTrue(doc.contains("crazy spider client-only particle spawn-source smoke"));
        assertTrue(doc.contains("actual Crazy Spider client particle-trail visual feel"));
        assertTrue(doc.contains("Crazy Spider particle-trail follow-up visual feel remains manual"));
        assertTrue(doc.contains("actual long-running Crazy Spider combat/pathfinding feel remains manual"));
        assertTrue(doc.contains("actual Crazy Skeleton renderer/model visual feel"));
        assertTrue(doc.contains("actual Crazy Spider renderer/model visual feel"));
        assertTrue(doc.contains("cavenic bear natural spawn placement registration"));
        assertTrue(doc.contains("cavenic bear CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("docs/cavenia-crazy-roster-natural-spawn-boundary.md"));
        assertTrue(doc.contains("inactive Cavenia dimension/provider foundation boundary"));
        assertTrue(doc.contains("no active `cavernreborn:cavenia` level resolves at runtime"));
        assertTrue(doc.contains("docs/cavenia-dimension-provider-foundation-boundary.md"));
        assertTrue(doc.contains("docs/cavenia-dimension-key-type-contract-boundary.md"));
        assertTrue(doc.contains("inactive Cavenia dimension key/type contract boundary"));
        assertTrue(doc.contains("inactive Cavenia biome-provider contract boundary"));
        assertTrue(doc.contains("docs/cavenia-biome-provider-contract-boundary.md"));
        assertTrue(doc.contains("inactive Cavenia VEINS/content-pipeline contract boundary"));
        assertTrue(doc.contains("docs/cavenia-veins-content-pipeline-contract-boundary.md"));
        assertTrue(doc.contains("inactive Cavenia chunk-generator/terrain-pipeline contract boundary"));
        assertTrue(doc.contains("docs/cavenia-chunk-generator-terrain-pipeline-contract-boundary.md"));
        assertTrue(doc.contains("inactive Cavenia cave-carver / `MapGenCaveniaCaves` contract boundary"));
        assertTrue(doc.contains("docs/cavenia-cave-carver-mapgen-contract-boundary.md"));
        assertTrue(doc.contains("inactive Cavenia population / lakes / falls / `cavenic_shroom` contract boundary"));
        assertTrue(doc.contains("docs/cavenia-population-lakes-falls-shroom-contract-boundary.md"));
        assertTrue(doc.contains("inactive Cavenia mirage entry/access contract boundary"));
        assertTrue(doc.contains("no registered `cavernreborn:mirage_book` item exists at runtime"));
        assertTrue(doc.contains("the Cavenia mirage entry/access contract boundary note at `docs/cavenia-mirage-entry-access-contract-boundary.md`"));
        assertTrue(doc.contains("inactive Cavenia spawn-provider / crazy-roster activation contract boundary"));
        assertTrue(doc.contains("inactive Caveman / Cavenia normal-roster boundary"));
        assertTrue(doc.contains("Cavenia Active Foundation Readiness / Implementation Plan"));
        assertTrue(doc.contains("docs/cavenia-active-foundation-readiness-plan.md"));
        assertTrue(doc.contains("inactive Cavenia active-foundation readiness-plan boundary"));
        assertTrue(doc.contains("Cavenia Active Foundation Technical Spike"));
        assertTrue(doc.contains("docs/cavenia-active-foundation-technical-spike.md"));
        assertTrue(doc.contains("inactive Cavenia active-foundation technical-spike boundary"));
        assertTrue(doc.contains("Cavenia Runtime Key / Inactive Dimension Scaffold MVP"));
        assertTrue(doc.contains("docs/cavenia-runtime-key-inactive-dimension-scaffold-mvp.md"));
        assertTrue(doc.contains("inert Cavenia runtime-key / inactive-dimension scaffold MVP"));
        assertTrue(doc.contains("Cavenia Terrain Generator Foundation / Non-Runtime MVP"));
        assertTrue(doc.contains("docs/cavenia-terrain-generator-foundation-non-runtime-mvp.md"));
        assertTrue(doc.contains("non-runtime Cavenia terrain-generator foundation MVP"));
        assertTrue(doc.contains("Cavenia Cave Carver Policy / Non-Runtime MVP"));
        assertTrue(doc.contains("docs/cavenia-cave-carver-policy-non-runtime-mvp.md"));
        assertTrue(doc.contains("non-runtime Cavenia cave-carver policy MVP"));
        assertTrue(doc.contains("Cavenia Biome Top/Filter Policy / Non-Runtime MVP"));
        assertTrue(doc.contains("docs/cavenia-biome-top-filter-policy-non-runtime-mvp.md"));
        assertTrue(doc.contains("non-runtime Cavenia biome top/filter policy MVP"));
        assertTrue(doc.contains("Cavenia VEINS / Content Policy / Non-Runtime MVP"));
        assertTrue(doc.contains("docs/cavenia-veins-content-policy-non-runtime-mvp.md"));
        assertTrue(doc.contains("non-runtime Cavenia VEINS/content policy MVP"));
        assertTrue(doc.contains("Cavenia Population Policy / Non-Runtime MVP"));
        assertTrue(doc.contains("docs/cavenia-population-policy-non-runtime-mvp.md"));
        assertTrue(doc.contains("non-runtime Cavenia population policy MVP"));
        assertTrue(doc.contains("Cavenia Active Generator Technical Scaffold / MVP"));
        assertTrue(doc.contains("docs/cavenia-active-generator-technical-scaffold-mvp.md"));
        assertTrue(doc.contains("non-registered Cavenia active-generator technical scaffold MVP"));
        assertTrue(doc.contains("Cavenia Active Generator Runtime Prototype / Inert App-Side Bridge MVP"));
        assertTrue(doc.contains("docs/cavenia-active-generator-runtime-prototype-inert-bridge-mvp.md"));
        assertTrue(doc.contains("inert app-side Cavenia generator bridge MVP"));
        assertTrue(doc.contains("Cavenia Active Generator Registration / Inert Activation Boundary MVP"));
        assertTrue(doc.contains("docs/cavenia-active-generator-registration-inert-boundary-mvp.md"));
        assertTrue(doc.contains("inert Cavenia generator registration boundary MVP"));
        assertTrue(doc.contains("Cavenia Chunk Generator / Biome Source Unregistered Skeleton MVP"));
        assertTrue(doc.contains("docs/cavenia-generator-biome-source-unregistered-skeleton-mvp.md"));
        assertTrue(doc.contains("unregistered Cavenia generator/biome-source skeleton MVP"));
        assertTrue(doc.contains("Cavenia Generator Runtime Contract Interfaces / Non-Registered MVP"));
        assertTrue(doc.contains("docs/cavenia-generator-runtime-contracts-non-registered-mvp.md"));
        assertTrue(doc.contains("non-registered Cavenia generator runtime-contract MVP"));
        assertTrue(doc.contains("Cavenia Generator Activation-Readiness Runtime Host Contracts MVP"));
        assertTrue(doc.contains("docs/cavenia-generator-activation-readiness-host-contracts-mvp.md"));
        assertTrue(doc.contains("non-registered Cavenia activation-readiness host-contract MVP"));
        assertTrue(doc.contains("Cavenia Generator Host / Biome Source Strategy Host Split Contracts MVP"));
        assertTrue(doc.contains("docs/cavenia-generator-host-biome-source-strategy-split-contracts-mvp.md"));
        assertTrue(doc.contains("non-registered Cavenia generator-host / biome-source-strategy split-contract MVP"));
        assertTrue(doc.contains("Cavenia Dimension-Resource / Access-Travel / Spawn-Host Split Contracts MVP"));
        assertTrue(doc.contains("docs/cavenia-dimension-access-spawn-split-contracts-mvp.md"));
        assertTrue(doc.contains("non-registered Cavenia dimension-resource / access-travel / spawn-host split-contract MVP"));
        assertTrue(doc.contains("Cavenia Worldgen-Resource Host Split Contracts MVP"));
        assertTrue(doc.contains("docs/cavenia-worldgen-resource-host-split-contracts-mvp.md"));
        assertTrue(doc.contains("non-registered Cavenia worldgen-resource split-contract MVP"));
        assertTrue(doc.contains("`CaveniaPopulationPolicy.generateLakesDefaultEnabled()` remains pinned to `true`"));
        assertTrue(doc.contains("`CaveniaGeneratorScaffold` now resolves from `core`"));
        assertTrue(doc.contains("`CaveniaGeneratorBridge` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("`CaveniaGeneratorRegistrationBoundary` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("`CaveniaGeneratorSkeleton` and `CaveniaBiomeSelectionSkeleton` now resolve from `app-neoforge`"));
        assertTrue(doc.contains("`CaveniaGeneratorHostContracts` and `CaveniaBiomeSourceStrategyContracts` now resolve from `app-neoforge`"));
        assertTrue(doc.contains("`CaveniaDimensionResourceContracts`, `CaveniaAccessTravelContracts` and `CaveniaSpawnHostContracts` now resolve from `app-neoforge`"));
        assertTrue(doc.contains("`CaveniaWorldgenResourceContracts` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("`CaveniaGeneratorRuntimeContracts` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("`CaveniaActivationReadinessHosts` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("runtime generator registration as false"));
        assertTrue(doc.contains("codec registration and generator registry entry registration as false"));
        assertTrue(doc.contains("`CaveniaVeinsContentPolicy.entries().size()` remains pinned to `13`"));
        assertTrue(doc.contains("`CaveniaVeinsContentPolicy.totalWeight()` remains pinned to `436`"));
        assertTrue(doc.contains("`CaveniaSpawnProviderPolicy` still keeps `EntityCaveman -> deferred:caveman`"));
        assertTrue(doc.contains("dimension resources absent"));
        assertTrue(doc.contains("level creation, teleport and spawning blocked"));
        assertTrue(doc.contains("configured carver/configured feature/placed feature/biome modifier/biome tag resources absent"));
        assertTrue(doc.contains("no `CAVERN` resource reuse is accepted as Cavenia parity"));
        assertTrue(doc.contains("no registered `cavernreborn:caveman` entity type exists at runtime"));
        assertTrue(doc.contains("Cavenia Runtime BiomeSource First Implementation Decision / Guardrails MVP"));
        assertTrue(doc.contains("runtime-biome-source first-implementation decision/guardrails MVP"));
        assertTrue(doc.contains("`CaveniaRuntimeBiomeSourceFirstImplementationDecision` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("selected decision is `PROCEED_WITH_UNREGISTERED_RUNTIME_BIOME_SOURCE_SKELETON_NEXT`"));
        assertTrue(doc.contains("decision is to proceed with unregistered skeleton next while runtime biome source is not implemented in this slice"));
        assertTrue(doc.contains("activation is not allowed in this slice, guardrail count remains `14` and all guardrails are enforced in this slice"));
        assertTrue(doc.contains("no runtime activation is allowed by guardrails and next slice may add only an unregistered skeleton"));
        assertTrue(doc.contains("next slice may not add codec implementation, may not register codec and may not register biome-source type"));
        assertTrue(doc.contains("next slice may not use registry lookup access, may not add dimension JSON/type JSON and may not create an active Cavenia level"));
        assertTrue(doc.contains("next slice may not add worldgen resources, may not add access/teleport, may not add spawning and may not register `cavernreborn:caveman`"));
        assertTrue(doc.contains("selected-surface readiness matrix remains ready while selected-surface runtime remains blocked"));
        assertTrue(doc.contains("selected-surface readiness item count remains `68` and global readiness matrix total/blocked requirement counts remain `46/46`"));
        assertTrue(doc.contains("runtime biome source is not ready, runtime biome source is not registered, codec is not registered and registry lookup access is not ready"));
        assertTrue(doc.contains("the runtime-biome-source first-implementation decision/guardrails note at `docs/cavenia-runtime-biome-source-first-implementation-decision-guardrails-mvp.md`"));
        assertTrue(doc.contains("Cavenia Guarded Unregistered Real BiomeSource Subclass Stub MVP"));
        assertTrue(doc.contains("guarded unregistered real `BiomeSource` subclass stub MVP"));
        assertTrue(doc.contains("`CaveniaRuntimeBiomeSource` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("it extends Minecraft `BiomeSource`, but normal runtime construction is not allowed"));
        assertTrue(doc.contains("unsupported method stubs only"));
        assertTrue(doc.contains("codec method is stubbed, possible-biomes collection method is stubbed and noise-biome method is stubbed"));
        assertTrue(doc.contains("usable runtime behavior is not ready, usable codec implementation is not ready, codec is not registered and biome-source type is not registered"));
        assertTrue(doc.contains("registry lookup access is not ready, holder/resource-key conversion is not ready and dimension binding is not ready"));
        assertTrue(doc.contains("go/no-go guardrails remain enforced, selected-surface readiness item count remains `68` and global readiness matrix total/blocked requirement counts remain `46/46`"));
        assertTrue(doc.contains("dimension JSON/type JSON remain absent, Cavenia cannot activate now and `EntityCaveman -> deferred:caveman` remains unchanged"));
        assertTrue(doc.contains("the guarded runtime-biome-source subclass stub note at `docs/cavenia-guarded-unregistered-real-biome-source-subclass-stub-mvp.md`"));
        assertTrue(doc.contains("Cavenia Runtime BiomeSource Holder/Resource-Key Conversion Readiness MVP"));
        assertTrue(doc.contains("Holder/Resource-Key Conversion Readiness MVP"));
        assertTrue(doc.contains("`CaveniaRuntimeBiomeSourceHolderConversionReadiness` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("holder conversion readiness is ready, candidate key format is pinned and registry lookup is required for future runtime conversion"));
        assertTrue(doc.contains("runtime conversion implementation is not ready, registry lookup access is not ready, holder resolution is not ready, resource-key conversion is not ready and resource-location conversion is not ready"));
        assertTrue(doc.contains("possible-biomes runtime is not ready, noise-biome runtime is not ready, missing-biome fallback is not ready and real holder conversion is still deferred"));
        assertTrue(doc.contains("candidate entry count remains `14`, candidate inventory is ready and candidate keys remain string-only"));
        assertTrue(doc.contains("designated subclass remains ready, codec method shape stub remains ready, usable codec implementation is not ready and biome-source type registration is not ready"));
        assertTrue(doc.contains("normal runtime construction is not allowed, unsupported method stubs only remain in place and `EntityCaveman -> deferred:caveman` remains unchanged"));
        assertTrue(doc.contains("the holder/resource-key conversion readiness note at `docs/cavenia-runtime-biome-source-holder-resource-key-conversion-readiness-mvp.md`"));
        assertTrue(doc.contains("Cavenia Runtime BiomeSource Fallback Policy Readiness MVP"));
        assertTrue(doc.contains("Fallback Policy Readiness MVP"));
        assertTrue(doc.contains("`CaveniaRuntimeBiomeSourceFallbackPolicyReadiness` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("fallback policy readiness is ready, fallback policy source is pinned and fallback trigger unparseable candidate id is pinned"));
        assertTrue(doc.contains("fallback trigger unresolved resource key is pinned, fallback trigger missing holder is pinned and fallback trigger empty possible biomes is pinned"));
        assertTrue(doc.contains("fallback legacy biome name is pinned, fallback candidate modern key is pinned, fallback registry verification is deferred and fallback holder resolution is deferred"));
        assertTrue(doc.contains("fallback runtime usage is deferred, runtime fallback implementation is not ready and registry lookup is required for future runtime fallback"));
        assertTrue(doc.contains("registry lookup access is not ready, fallback is not registry verified, fallback holder is not resolved and fallback runtime is not ready"));
        assertTrue(doc.contains("possible-biomes fallback is not ready, noise-biome fallback is not ready and real fallback policy is still deferred"));
        assertTrue(doc.contains("fallback legacy biome name is `PLAINS`, fallback candidate modern biome key is `minecraft:plains` and fallback candidate exists in inventory"));
        assertTrue(doc.contains("fallback candidate entry count remains `14`, candidate inventory is ready and candidate keys remain string-only"));
        assertTrue(doc.contains("holder conversion readiness is ready, holder conversion runtime is not ready, codec method shape stub is ready and designated subclass remains ready"));
        assertTrue(doc.contains("designated subclass runtime is not ready, usable codec implementation is not ready, codec is not registered and biome-source type is not registered"));
        assertTrue(doc.contains("normal runtime construction is not allowed, unsupported method stubs only remain in place and `EntityCaveman -> deferred:caveman` remains unchanged"));
        assertTrue(doc.contains("the fallback-policy readiness note at `docs/cavenia-runtime-biome-source-fallback-policy-readiness-mvp.md`"));
        assertTrue(doc.contains("Cavenia Runtime BiomeSource Possible-Biomes Readiness MVP"));
        assertTrue(doc.contains("Possible-Biomes Readiness MVP"));
        assertTrue(doc.contains("`CaveniaRuntimeBiomeSourcePossibleBiomesReadiness` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("possible-biomes readiness is ready, possible-biomes method shape is pinned, candidate keys source is pinned, candidate entry count is pinned, candidate ordering policy is pinned, candidate deduplication policy is pinned, holder conversion dependency is pinned and fallback-included-if-empty policy is pinned"));
        assertTrue(doc.contains("runtime holder stream is not ready, collectPossibleBiomes implementation is not ready and registry lookup is required for future runtime possible-biomes"));
        assertTrue(doc.contains("registry lookup access is not ready, possible-biomes runtime is not ready and real possible-biomes is still deferred"));
        assertTrue(doc.contains("candidate entry count remains `14`, candidate inventory is ready and candidate keys remain string-only"));
        assertTrue(doc.contains("fallback policy readiness is ready, fallback policy runtime is not ready, fallback legacy biome name is `PLAINS`, fallback candidate modern biome key is `minecraft:plains`, fallback included if empty is true and fallback runtime is not ready"));
        assertTrue(doc.contains("holder conversion readiness is ready, holder conversion runtime is not ready, holder resolution is not ready, resource-key conversion is not ready and resource-location conversion is not ready"));
        assertTrue(doc.contains("codec method shape stub is ready, designated subclass remains ready and designated subclass runtime is not ready"));
        assertTrue(doc.contains("usable codec implementation is not ready, codec is not registered and biome-source type is not registered"));
        assertTrue(doc.contains("normal runtime construction is not allowed, unsupported method stubs only remain in place, `collectPossibleBiomes()` remains stubbed, `getNoiseBiome(...)` remains stubbed, `codec()` remains stubbed and `EntityCaveman -> deferred:caveman` remains unchanged"));
        assertTrue(doc.contains("the possible-biomes readiness note at `docs/cavenia-runtime-biome-source-possible-biomes-readiness-mvp.md`"));
        assertTrue(doc.contains("Cavenia Runtime BiomeSource Noise-Biome Selection Readiness MVP"));
        assertTrue(doc.contains("Noise-Biome Selection Readiness MVP"));
        assertTrue(doc.contains("`CaveniaRuntimeBiomeSourceNoiseBiomeSelectionReadiness` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("noise-biome selection readiness is ready, noise-biome method shape is pinned, coordinate input shape is pinned, climate sampler input shape is pinned"));
        assertTrue(doc.contains("weight-value derivation decision is pinned, weighted selection source is pinned, adapter selection source is pinned, candidate key output source is pinned, holder conversion dependency is pinned, fallback policy source is pinned and possible-biomes constraint is pinned"));
        assertTrue(doc.contains("runtime holder return is not ready, getNoiseBiome implementation is not ready and registry lookup is required for future runtime noise-biome"));
        assertTrue(doc.contains("registry lookup access is not ready, noise-biome runtime is not ready and real noise-biome selection is still deferred"));
        assertTrue(doc.contains("weighted selection algorithm is ready, weighted selection runtime is not ready and weighted selection total weight remains `675`"));
        assertTrue(doc.contains("adapter shape is ready and adapter runtime is not ready, candidate entry count remains `14`, candidate inventory is ready and candidate keys remain string-only"));
        assertTrue(doc.contains("holder conversion readiness is ready, holder conversion runtime is not ready, holder resolution is not ready, resource-key conversion is not ready and resource-location conversion is not ready"));
        assertTrue(doc.contains("fallback policy readiness is ready, fallback policy runtime is not ready, fallback legacy biome name is `PLAINS`, fallback candidate modern biome key is `minecraft:plains`"));
        assertTrue(doc.contains("possible-biomes readiness is ready and possible-biomes runtime is not ready, codec method shape stub is ready, designated subclass remains ready and designated subclass runtime is not ready"));
        assertTrue(doc.contains("usable codec implementation is not ready, codec is not registered and biome-source type is not registered, normal runtime construction is not allowed, unsupported method stubs only remain in place"));
        assertTrue(doc.contains("`collectPossibleBiomes()` remains stubbed, `getNoiseBiome(...)` remains stubbed, `codec()` remains stubbed and `EntityCaveman -> deferred:caveman` remains unchanged"));
        assertTrue(doc.contains("the noise-biome selection readiness note at `docs/cavenia-runtime-biome-source-noise-biome-selection-readiness-mvp.md`"));
        assertTrue(doc.contains("Cavenia Runtime BiomeSource Readiness Chain Consolidation / Next Decision MVP"));
        assertTrue(doc.contains("Readiness Chain Consolidation / Next Decision MVP"));
        assertTrue(doc.contains("`CaveniaRuntimeBiomeSourceReadinessChainConsolidation` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("readiness-chain consolidation is ready, all current readiness layers are ready, runtime-ready layer count is `0`, consolidated readiness layer count is `6`"));
        assertTrue(doc.contains("the selected next decision is `PROCEED_WITH_SELECTOR_INPUT_DERIVATION_GO_NO_GO_NEXT`, selector-input-derivation go/no-go is next, selector-input derivation is not pinned, selector-input derivation implementation is not ready, selector-input derivation runtime is not ready"));
        assertTrue(doc.contains("next slice may add selector-input-derivation go/no-go decision, the next slice may not implement selector-input derivation or use coordinates or climate sampler for runtime selection"));
        assertTrue(doc.contains("the next slice may not make `getNoiseBiome(...)` or `collectPossibleBiomes()` usable, the next slice may not use registry lookup access, resolve holders, implement resource-location conversion, implement resource-key conversion, add fallback implementation, add usable codec implementation, register codec, register biome-source type, add dimension JSON/type JSON, create an active Cavenia level, add worldgen resources, add access/teleport, add spawning or register Caveman entity"));
        assertTrue(doc.contains("the current codec, holder-conversion, fallback, possible-biomes and noise-biome readiness layers all remain ready while every runtime surface remains blocked"));
        assertTrue(doc.contains("the readiness-chain consolidation note at `docs/cavenia-runtime-biome-source-readiness-chain-consolidation-next-decision-mvp.md`"));
        assertTrue(doc.contains("Cavenia Runtime BiomeSource Selector Input Derivation Go/No-Go MVP"));
        assertTrue(doc.contains("Selector Input Derivation Go/No-Go MVP"));
        assertTrue(doc.contains("`CaveniaRuntimeBiomeSourceSelectorInputDerivationGoNoGoDecision` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("selected decision is `PROCEED_WITH_SELECTOR_INPUT_DERIVATION_READINESS_NEXT`, decision is go for selector-input derivation readiness next, decision is readiness-only for next slice"));
        assertTrue(doc.contains("selector-input derivation readiness is not implemented in this slice, selector-input derivation policy is not pinned in this slice, selector-input derivation implementation is not ready and selector-input derivation runtime is not ready"));
        assertTrue(doc.contains("guardrail count is `17`, all guardrails are enforced in this slice, allowed next-slice readiness action count is `4`, allowed next-slice runtime action count is `0` and no runtime action is allowed by guardrails"));
        assertTrue(doc.contains("next slice may add selector-input derivation readiness, may pin coordinate input policy, may pin climate sampler input policy and may pin weight-value derivation policy"));
        assertTrue(doc.contains("next slice may not implement selector-input derivation, may not use coordinates or climate sampler for runtime selection, may not make `getNoiseBiome(...)` or `collectPossibleBiomes()` usable, and may not use registry lookup access or resolve holders"));
        assertTrue(doc.contains("readiness-chain consolidation is ready, readiness-chain runtime is not ready, readiness-chain selected next decision matches, all current readiness layers are ready, runtime-ready layer count remains `0` and consolidated readiness layer count remains `6`"));
        assertTrue(doc.contains("noise-biome selection readiness is ready, noise-biome selection runtime is not ready, coordinate input shape is pinned, climate sampler input shape is pinned, weight-value derivation decision is pinned and weighted selection total weight remains `675`"));
        assertTrue(doc.contains("candidate entry count remains `14`, fallback legacy biome name is `PLAINS`, fallback candidate modern biome key is `minecraft:plains`, holder conversion readiness is ready, fallback policy readiness is ready, possible-biomes readiness is ready and codec method shape stub is ready"));
        assertTrue(doc.contains("designated subclass remains ready, usable runtime biome source is not ready, registry lookup access is not ready, usable codec implementation is not ready, codec is not registered and biome-source type is not registered"));
        assertTrue(doc.contains("the selector-input derivation go/no-go note at `docs/cavenia-runtime-biome-source-selector-input-derivation-go-no-go-mvp.md`"));
        assertTrue(doc.contains("Cavenia Runtime BiomeSource Selector Input Derivation Readiness MVP"));
        assertTrue(doc.contains("Selector Input Derivation Readiness MVP"));
        assertTrue(doc.contains("`CaveniaRuntimeBiomeSourceSelectorInputDerivationReadiness` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("selector-input derivation readiness is ready, method input shape is pinned, coordinate input policy is pinned, climate sampler input policy is pinned, selector input output shape is pinned"));
        assertTrue(doc.contains("deterministic derivation policy is pinned, pure non-runtime policy is pinned, weighted selector compatibility is pinned, adapter query compatibility is pinned, normalization policy is pinned, negative coordinate stability policy is pinned, chunk-boundary stability policy is pinned, no-world-or-registry dependency is pinned and no-random-or-mutable-state dependency is pinned"));
        assertTrue(doc.contains("selector-input derivation implementation is not ready, selector-input derivation runtime is not ready, coordinate runtime selection is not ready, climate sampler runtime selection is not ready and real selector-input derivation is still deferred"));
        assertTrue(doc.contains("actual derivation formula is not pinned and actual derivation formula is not implemented, go/no-go decision is ready and go/no-go runtime is not ready"));
        assertTrue(doc.contains("readiness-chain consolidation is ready and readiness-chain runtime is not ready, all current readiness layers are ready, runtime-ready layer count remains `0` and consolidated readiness layer count remains `6`"));
        assertTrue(doc.contains("noise-biome selection readiness is ready and noise-biome selection runtime is not ready, weighted selection total weight remains `675`, adapter shape is ready and adapter runtime is not ready"));
        assertTrue(doc.contains("candidate entry count remains `14`, candidate inventory is ready and candidate keys are string-only, fallback legacy biome name is `PLAINS`, fallback candidate modern biome key is `minecraft:plains`"));
        assertTrue(doc.contains("holder conversion readiness is ready, holder conversion runtime is not ready, holder resolution is not ready, resource-location conversion is not ready and resource-key conversion is not ready"));
        assertTrue(doc.contains("possible-biomes readiness is ready and possible-biomes runtime is not ready, fallback policy readiness is ready and fallback policy runtime is not ready"));
        assertTrue(doc.contains("codec method shape stub is ready and codec method shape runtime is not ready, designated subclass remains ready and designated subclass runtime is not ready"));
        assertTrue(doc.contains("runtime holder return is not ready, collectPossibleBiomes implementation is not ready, getNoiseBiome implementation is not ready, usable runtime biome source is not ready, registry lookup access is not ready"));
        assertTrue(doc.contains("usable codec implementation is not ready, codec is not registered and biome-source type is not registered, normal runtime construction is not allowed, unsupported method stubs only remain in place"));
        assertTrue(doc.contains("selected-surface readiness item count remains `68`, global readiness matrix total requirement count remains `46`, global readiness matrix blocked requirement count remains `46`, dimension JSON is absent, dimension type JSON is absent, Caveman remains deferred and `EntityCaveman -> deferred:caveman` remains unchanged"));
        assertTrue(doc.contains("the selector-input derivation readiness note at `docs/cavenia-runtime-biome-source-selector-input-derivation-readiness-mvp.md`"));
        assertTrue(doc.contains("Cavenia Runtime BiomeSource Selector Input Derivation Implementation Go/No-Go MVP"));
        assertTrue(doc.contains("Selector Input Derivation Implementation Go/No-Go MVP"));
        assertTrue(doc.contains("`CaveniaRuntimeBiomeSourceSelectorInputDerivationImplementationGoNoGoDecision` now resolves from `app-neoforge`"));
        assertTrue(doc.contains("selected decision is `PROCEED_WITH_PURE_NON_RUNTIME_SELECTOR_INPUT_DERIVATION_ALGORITHM_NEXT`, decision is go for pure non-runtime algorithm next, selector-input derivation algorithm is not implemented in this slice"));
        assertTrue(doc.contains("guardrail count is `18`, all guardrails are enforced in this slice, allowed next-slice pure algorithm action count is `4`, allowed next-slice runtime action count is `0` and no runtime action is allowed by guardrails"));
        assertTrue(doc.contains("next slice may add pure non-runtime selector-input algorithm, may use integer coordinate inputs, may return signed int selector input and may delegate normalization to existing selector/adapter"));
        assertTrue(doc.contains("next slice may not call climate sampler methods, may not import Minecraft runtime APIs, may not wire into `getNoiseBiome(...)`, may not make `getNoiseBiome(...)` or `collectPossibleBiomes()` usable"));
        assertTrue(doc.contains("selector-input derivation readiness is ready, selector-input derivation readiness runtime is not ready, selector-input derivation output shape is pinned, actual derivation formula is not pinned and actual derivation formula is not implemented"));
        assertTrue(doc.contains("the selector-input derivation implementation go/no-go note at `docs/cavenia-runtime-biome-source-selector-input-derivation-implementation-go-no-go-mvp.md`"));
        assertTrue(doc.contains("docs/caveman-cavenia-normal-roster-boundary.md"));
        assertTrue(doc.contains("no checked-in normal `CAVERN` crazy biome modifiers or crazy biome tags exist"));
        assertTrue(doc.contains("the Cavenia spawn-provider / crazy-roster activation contract boundary note at `docs/cavenia-spawn-provider-crazy-roster-activation-contract-boundary.md`"));
        assertTrue(doc.contains("cavenic bear biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic bear biome tag resolution"));
        assertTrue(doc.contains("cavenic bear legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic bear legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic bear generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic bear legacy hostile player-target goal smoke"));
        assertTrue(doc.contains("cavenic bear legacy hurt-by-target retaliation smoke"));
        assertTrue(doc.contains("cavenic bear non-player target baseline smoke"));
        assertTrue(doc.contains("cavenic bear legacy melee-goal registration smoke"));
        assertTrue(doc.contains("cavenic bear legacy melee reach smoke"));
        assertTrue(doc.contains("cavenic bear legacy standing-warning threshold smoke"));
        assertTrue(doc.contains("cavenic bear legacy panic-goal registration smoke"));
        assertTrue(doc.contains("cavenic bear legacy burning-only panic-trigger smoke"));
        assertTrue(doc.contains("cavenic bear freeze panic rejection smoke"));
        assertTrue(doc.contains("cavenic bear explicit passive/movement AI equivalence boundary against the inherited modern polar bear base"));
        assertTrue(doc.contains("any broader Cavenic Witch AI-goal or target-selector rewrite beyond the restored ranged-potion slice"));
        assertTrue(doc.contains("actual long-running Cavenic Witch fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-run cavenic witch orb-drop rate balance"));
        assertTrue(doc.contains("actual long-run Cavenic Witch population balance inside CAVERN"));
        assertTrue(doc.contains("actual long-run Cavenic Spider population balance inside CAVERN"));
        assertFalse(doc.contains("Cavenic Spider natural spawning in this baseline slice"));
        assertFalse(doc.contains("Cavenic Witch natural spawning, because that bounded follow-up is still out of scope for the current baseline slice"));
        assertTrue(doc.contains("actual long-run cavenic creeper orb-drop rate balance"));
        assertTrue(doc.contains("actual long-running Cavenic Creeper fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-run Cavenic Creeper population balance inside CAVERN"));
        assertTrue(doc.contains("actual long-run cavenic zombie orb-drop rate balance"));
        assertTrue(doc.contains("actual long-run cavenic skeleton orb-drop rate balance"));
        assertTrue(doc.contains("actual long-running Cavenic Zombie fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-running Cavenic Skeleton fire/lava gameplay feel"));
        assertTrue(doc.contains("actual Cavenic Creeper fuse timing, explosion feel and block-damage behavior"));
        assertTrue(doc.contains("actual long-run Cavenic Skeleton population balance inside CAVERN"));
        assertTrue(doc.contains("actual Cavenic Bear renderer/model visual feel"));
        assertTrue(doc.contains("actual long-run Cavenic Bear drop-rate balance, although the current source inspection found no direct custom bear loot branch beyond the vanilla polar bear baseline"));
        assertTrue(doc.contains("actual long-running Cavenic Bear fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-running Cavenic Bear melee/pathfinding feel"));
        assertTrue(doc.contains("actual long-running Cavenic Bear panic/pathfinding feel"));
        assertTrue(doc.contains("actual long-running Cavenic Bear passive follow/wander/look pathfinding feel"));
        assertTrue(doc.contains("actual Cavenic Bear anger/pathfinding feel"));
        assertTrue(doc.contains("actual long-run Cavenic Bear population balance inside CAVERN"));
        assertTrue(doc.contains("actual long-running Crazy Zombie fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-run Crazy Zombie orb-drop rate balance"));
        assertTrue(doc.contains("Crazy Zombie custom loot beyond the restored inherited `cavenic_orb` branch"));
        assertTrue(doc.contains("Crazy Skeleton natural spawning, because the inspected legacy path still belongs to the old Cavenia-only crazy-roster provider/config branch rather than the current `CAVERN` biome-spawn pattern"));
        assertTrue(doc.contains("Crazy Skeleton custom loot beyond the restored inherited `cavenic_orb` branch"));
        assertTrue(doc.contains("actual long-running Crazy Skeleton fire/lava gameplay feel"));
        assertTrue(doc.contains("actual client-visible Crazy Skeleton boss-bar feel remains manual"));
        assertTrue(doc.contains("Crazy Skeleton particle-trail follow-up"));
        assertTrue(doc.contains("actual long-running Crazy Skeleton ranged combat feel remains manual"));
        assertTrue(doc.contains("natural spawning remains deferred through Cavenia boundary"));
        assertTrue(doc.contains("legacy Cavenic Bow Rapid/Torch custom projectile behavior and client feel beyond the current bounded Snipe, Rapid and Torch slices"));
        assertTrue(doc.contains("legacy `EntityCavenicArrow` parity beyond the current vanilla-compatible skeleton/player projectile boundary"));
        assertTrue(doc.contains("actual long-run Cavenic Zombie population balance inside CAVERN"));
        assertTrue(doc.contains("actual underwater aquamarine mining feel"));
        assertTrue(doc.contains("actual brittle magnite mining feel"));
        assertTrue(doc.contains("portal UX"));
        assertTrue(doc.contains("rendering"));
    }

    @Test
    void runtimeSmokeScriptExists() {
        assertTrue(Files.exists(SCRIPT));
        assertTrue(Files.isExecutable(SCRIPT));
    }

    private static Path resolveProjectFile(String first, String... more) {
        Path current = Path.of("").toAbsolutePath();

        for (int i = 0; i < 5 && current != null; i++) {
            Path candidate = current.resolve(Path.of(first, more));
            if (Files.exists(candidate)) {
                return candidate;
            }
            current = current.getParent();
        }

        throw new IllegalStateException("Could not resolve project file: " + Path.of(first, more));
    }
}
