package com.richardkenway.cavernreborn.app.gametest;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;

class CavernRuntimeSmokeDocumentationTest {
    private static final Path README = resolveProjectFile("README.md");
    private static final Path RUNTIME_SMOKE = resolveProjectFile("docs", "runtime-smoke.md");
    private static final Path SCRIPT = resolveProjectFile("scripts", "runtime-smoke.sh");

    @Test
    void readmeDocumentsAutomatedRuntimeSmokeEntryPoint() throws IOException {
        String readme = Files.readString(README);

        assertTrue(readme.contains("Automated Runtime Validation"));
        assertTrue(readme.contains("NeoForge GameTest"));
        assertTrue(readme.contains("docs/runtime-smoke.md"));
        assertTrue(readme.contains("./gradlew --no-daemon :app-neoforge:runGameTestServer"));
        assertTrue(readme.contains("scripts/runtime-smoke.sh"));
        assertTrue(readme.contains("hexcite"));
        assertTrue(readme.contains("randomite"));
        assertTrue(readme.contains("fissured_stone"));
        assertTrue(readme.contains("Mining Assist"));
        assertTrue(readme.contains("Miner's Orb MVP"));
        assertTrue(readme.contains("docs/miner-orb-mvp.md"));
        assertTrue(readme.contains("Ore Compass MVP"));
        assertTrue(readme.contains("docs/ore-compass-mvp.md"));
        assertTrue(readme.contains("bounded tracking UX follow-up"));
        assertTrue(readme.contains("track that target visually"));
        assertTrue(readme.contains("Hexcite Armor MVP"));
        assertTrue(readme.contains("docs/hexcite-armor-mvp.md"));
        assertTrue(readme.contains("Aquamarine Utility Tools MVP"));
        assertTrue(readme.contains("docs/aquamarine-tool-mvp.md"));
        assertTrue(readme.contains("Magnite Tool Set MVP"));
        assertTrue(readme.contains("docs/magnite-tool-mvp.md"));
        assertTrue(readme.contains("Magnite Armor MVP"));
        assertTrue(readme.contains("docs/magnite-armor-mvp.md"));
        assertTrue(readme.contains("Acresia Crop & Food MVP"));
        assertTrue(readme.contains("docs/acresia-crop-mvp.md"));
        assertTrue(readme.contains("renewable cave snack crop"));
        assertTrue(readme.contains("full farming system"));
        assertTrue(readme.contains("Cavenic Shroom & Orb MVP"));
        assertTrue(readme.contains("docs/cavenic-shroom-mvp.md"));
        assertTrue(readme.contains("hazardous flora"));
        assertTrue(readme.contains("Cavenic Bow Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-bow-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Bow Mode State & Cycling MVP"));
        assertTrue(readme.contains("docs/cavenic-bow-mode-state-mvp.md"));
        assertTrue(readme.contains("Cavenic Bow Snipe Mode MVP"));
        assertTrue(readme.contains("docs/cavenic-bow-snipe-mode-mvp.md"));
        assertTrue(readme.contains("Cavenic Bow Rapid Mode MVP"));
        assertTrue(readme.contains("docs/cavenic-bow-rapid-mode-mvp.md"));
        assertTrue(readme.contains("Cavenic Bow Torch Mode MVP"));
        assertTrue(readme.contains("docs/cavenic-bow-torch-mode-mvp.md"));
        assertTrue(readme.contains("Cavenic Zombie Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-zombie-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Zombie Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-zombie-natural-spawn-mvp.md"));
        assertTrue(readme.contains("Cavenic Zombie Legacy Orb Drop MVP"));
        assertTrue(readme.contains("docs/cavenic-zombie-orb-drop-mvp.md"));
        assertTrue(readme.contains("Cavenic Zombie Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-zombie-damage-behavior-mvp.md"));
        assertTrue(readme.contains("legacy `1/8` `cavenic_orb` drop"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity"));
        assertTrue(readme.contains("Cavenic Skeleton Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-skeleton-baseline-mvp.md"));
        assertTrue(readme.contains("second direct Cavenic mob foundation"));
        assertTrue(readme.contains("Cavenic Skeleton Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-skeleton-natural-spawn-mvp.md"));
        assertTrue(readme.contains("bounded CAVERN-only natural spawning"));
        assertTrue(readme.contains("Cavenic Skeleton Legacy Orb Drop MVP"));
        assertTrue(readme.contains("docs/cavenic-skeleton-orb-drop-mvp.md"));
        assertTrue(readme.contains("legacy `1/5` `cavenic_orb` drop"));
        assertTrue(readme.contains("Cavenic Skeleton Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-skeleton-damage-behavior-mvp.md"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity"));
        assertTrue(readme.contains("Cavenic Creeper Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-creeper-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Creeper Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-creeper-natural-spawn-mvp.md"));
        assertTrue(readme.contains("Cavenic Creeper Legacy Orb Drop MVP"));
        assertTrue(readme.contains("docs/cavenic-creeper-orb-drop-mvp.md"));
        assertTrue(readme.contains("Cavenic Creeper Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-creeper-damage-behavior-mvp.md"));
        assertTrue(readme.contains("Cavenic Creeper Legacy Fuse/Explosion MVP"));
        assertTrue(readme.contains("docs/cavenic-creeper-fuse-explosion-mvp.md"));
        assertTrue(readme.contains("third direct Cavenic mob foundation"));
        assertTrue(readme.contains("bounded CAVERN-only natural spawning"));
        assertTrue(readme.contains("legacy `1/5` `cavenic_orb` drop"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity"));
        assertTrue(readme.contains("legacy `Fuse = 15` and `ExplosionRadius = 5`"));
        assertTrue(readme.contains("Cavenic Spider Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-spider-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Spider Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-spider-natural-spawn-mvp.md"));
        assertTrue(readme.contains("Cavenic Spider Legacy Orb Drop MVP"));
        assertTrue(readme.contains("docs/cavenic-spider-orb-drop-mvp.md"));
        assertTrue(readme.contains("Cavenic Spider Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-spider-damage-behavior-mvp.md"));
        assertTrue(readme.contains("Cavenic Spider Blindness-On-Hit MVP"));
        assertTrue(readme.contains("docs/cavenic-spider-blindness-on-hit-mvp.md"));
        assertTrue(readme.contains("fourth direct Cavenic mob foundation"));
        assertTrue(readme.contains("bounded CAVERN-only natural spawning"));
        assertTrue(readme.contains("vanilla spider loot baseline"));
        assertTrue(readme.contains("legacy `1/8` `cavenic_orb` drop"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity"));
        assertTrue(readme.contains("legacy difficulty-scaled blindness-on-hit behavior"));
        assertTrue(readme.contains("Cavenic Witch Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-natural-spawn-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Legacy Loot MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-loot-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-damage-behavior-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Same-Type Projectile Immunity MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-projectile-immunity-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Friendship Targeting MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-friendship-targeting-mvp.md"));
        assertTrue(readme.contains("Cavenic Witch Custom Ranged Potion MVP"));
        assertTrue(readme.contains("docs/cavenic-witch-ranged-potion-mvp.md"));
        assertTrue(readme.contains("docs/cavenic-witch-magic-book-deferred.md"));
        assertTrue(readme.contains("fifth direct Cavenic mob foundation"));
        assertTrue(readme.contains("bounded CAVERN-only natural spawning"));
        assertTrue(readme.contains("vanilla witch loot baseline"));
        assertTrue(readme.contains("legacy `1/5` `cavenic_orb` drop appended on top of the vanilla witch loot baseline"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity behavior"));
        assertTrue(readme.contains("legacy same-type/self source-immunity behavior"));
        assertTrue(readme.contains("legacy same-type friendship-target rejection behavior"));
        assertTrue(readme.contains("restored legacy ranged-potion behavior for normal combat targets"));
        assertTrue(readme.contains("the modern non-witch Raider-heal branch remains an intentional bounded bridge"));
        assertTrue(readme.contains("the inspected legacy magic-book branch remains explicitly deferred because `ItemMagicBook` is still a broader subtype/NBT/capability spellbook system"));
        assertTrue(readme.contains("Cavenic Bear Baseline MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-baseline-mvp.md"));
        assertTrue(readme.contains("Cavenic Bear Natural Spawn MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-natural-spawn-mvp.md"));
        assertTrue(readme.contains("docs/cavenic-bear-loot-absent-or-deferred.md"));
        assertTrue(readme.contains("Cavenic Bear Legacy Damage Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-damage-behavior-mvp.md"));
        assertTrue(readme.contains("Cavenic Bear Legacy Hostile Targeting MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-hostile-targeting-mvp.md"));
        assertTrue(readme.contains("Cavenic Bear Legacy Melee Attack MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-melee-attack-mvp.md"));
        assertTrue(readme.contains("Cavenic Bear Legacy Panic Behavior MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-panic-behavior-mvp.md"));
        assertTrue(readme.contains("Cavenic Bear Passive / Movement AI Boundary MVP"));
        assertTrue(readme.contains("docs/cavenic-bear-passive-ai-equivalent-or-deferred.md"));
        assertTrue(readme.contains("sixth direct Cavenic mob foundation"));
        assertTrue(readme.contains("legacy texture on the vanilla polar bear renderer path"));
        assertTrue(readme.contains("vanilla polar bear loot baseline"));
        assertTrue(readme.contains("bounded CAVERN-only natural spawning"));
        assertTrue(readme.contains("the inspected legacy bear loot line remains explicitly absent because `EntityCavenicBear` never overrides `dropLoot(...)`"));
        assertTrue(readme.contains("legacy fall-damage reduction and fire-damage immunity behavior"));
        assertTrue(readme.contains("bounded legacy player-target / hurt-by-target hostility slice"));
        assertTrue(readme.contains("bounded legacy melee-attack behavior"));
        assertTrue(readme.contains("bounded legacy panic behavior"));
        assertTrue(readme.contains("the remaining passive/movement bear goals stay on the inherited modern polar bear base"));
        assertTrue(readme.contains("Crazy Zombie Baseline MVP"));
        assertTrue(readme.contains("docs/crazy-zombie-baseline-mvp.md"));
        assertTrue(readme.contains("docs/crazy-zombie-loot-mvp.md"));
        assertTrue(readme.contains("docs/crazy-zombie-damage-behavior-mvp.md"));
        assertTrue(readme.contains("docs/crazy-zombie-boss-bar-mvp.md"));
        assertTrue(readme.contains("docs/crazy-zombie-particle-trail-mvp.md"));
        assertTrue(readme.contains("docs/crazy-zombie-natural-spawn-absent-or-deferred.md"));
        assertTrue(readme.contains("first legacy crazy-variant foundation follow-up"));
        assertTrue(readme.contains("`crazy_zombie`"));
        assertTrue(readme.contains("inherited legacy `1/8` `cavenic_orb` drop appended on top of the vanilla zombie loot baseline"));
        assertTrue(readme.contains("inherited legacy fall-damage reduction and fire-damage immunity behavior"));
        assertTrue(readme.contains("legacy blue progress boss bar and sky-darkening boss-event branch"));
        assertTrue(readme.contains("legacy client-only portal-tinted particle trail"));
        assertTrue(readme.contains("Cavenia-only crazy-roster provider/config branch"));
        assertTrue(readme.contains("Crazy Skeleton Baseline MVP"));
        assertTrue(readme.contains("docs/crazy-skeleton-baseline-mvp.md"));
        assertTrue(readme.contains("second crazy-variant foundation follow-up"));
        assertTrue(readme.contains("`crazy_skeleton`"));
        assertTrue(readme.contains("vanilla skeleton loot baseline"));
        assertTrue(readme.contains("docs/crazy-skeleton-loot-mvp.md"));
        assertTrue(readme.contains("docs/crazy-skeleton-damage-behavior-mvp.md"));
        assertTrue(readme.contains("docs/crazy-skeleton-boss-bar-mvp.md"));
        assertTrue(readme.contains("inherited legacy `1/5` `cavenic_orb` drop is now restored explicitly on top of that same vanilla skeleton loot baseline"));
        assertTrue(readme.contains("inherited legacy fall-damage reduction and fire-damage immunity behavior are now restored explicitly on top of that same vanilla skeleton baseline"));
        assertTrue(readme.contains("legacy white progress boss bar and sky-darkening boss-event branch are now restored explicitly on top of that same vanilla skeleton baseline"));
        assertTrue(readme.contains("legacy `EntityAIAttackCavenicBow` path"));
        assertTrue(readme.contains("docs/crazy-skeleton-cavenic-bow-equipment-mvp.md"));
        assertTrue(readme.contains("docs/crazy-skeleton-ranged-ai-boundary.md"));
        assertTrue(readme.contains("guaranteed `Cavenic Bow` mainhand, forced `Infinity` enchantment and `1.0F` mainhand drop chance are now restored explicitly"));
        assertTrue(readme.contains("custom ranged AI identity stays intentionally deferred"));
        assertTrue(readme.contains("Crazy Creeper Baseline MVP"));
        assertTrue(readme.contains("docs/crazy-creeper-baseline-mvp.md"));
        assertTrue(readme.contains("docs/crazy-creeper-loot-mvp.md"));
        assertTrue(readme.contains("docs/crazy-creeper-damage-behavior-mvp.md"));
        assertTrue(readme.contains("docs/crazy-creeper-boss-bar-mvp.md"));
        assertTrue(readme.contains("docs/crazy-creeper-particle-trail-mvp.md"));
        assertTrue(readme.contains("third crazy-variant foundation follow-up"));
        assertTrue(readme.contains("`crazy_creeper`"));
        assertTrue(readme.contains("vanilla creeper loot baseline"));
        assertTrue(readme.contains("inherited legacy `1/5` `cavenic_orb` drop is now restored explicitly on top of that same vanilla creeper loot baseline"));
        assertTrue(readme.contains("inherited legacy fall-damage reduction and fire-damage immunity behavior are now restored explicitly on top of that same vanilla creeper baseline"));
        assertTrue(readme.contains("legacy green progress boss bar and sky-darkening boss-event branch are now restored explicitly on top of that same vanilla creeper baseline"));
        assertTrue(readme.contains("legacy client-only portal-tinted particle trail is now restored explicitly on top of that same vanilla creeper baseline through the shared `crazy_mob` particle mapping"));
        assertTrue(readme.contains("Crazy Creeper fuse/explosion and lightning/charged/swelling follow-ups remain intentionally deferred"));
        assertTrue(readme.contains("Crazy Spider Baseline MVP"));
        assertTrue(readme.contains("docs/crazy-spider-baseline-mvp.md"));
        assertTrue(readme.contains("docs/crazy-spider-loot-mvp.md"));
        assertTrue(readme.contains("fourth crazy-variant foundation follow-up"));
        assertTrue(readme.contains("`crazy_spider`"));
        assertTrue(readme.contains("vanilla spider loot baseline"));
        assertTrue(readme.contains("inherited legacy `1/8` `cavenic_orb` drop is now restored explicitly on top of that same vanilla spider loot baseline"));
        assertTrue(readme.contains("direct blindness/poison combat hooks plus inherited damage, boss and particle branches remain intentionally deferred"));
        assertTrue(readme.contains("vanilla zombie loot baseline"));
    }

    @Test
    void runtimeSmokeDocCoversCommandsAndScope() throws IOException {
        String doc = Files.readString(RUNTIME_SMOKE);

        assertTrue(doc.contains("NeoForge GameTest runtime smoke"));
        assertTrue(doc.contains("runtime registry availability for tranche 2 content"));
        assertTrue(doc.contains("acresia runtime registry ids"));
        assertTrue(doc.contains("acresia seed planting smoke"));
        assertTrue(doc.contains("acresia mature normal harvest smoke"));
        assertTrue(doc.contains("acresia shear-harvest regrowth smoke"));
        assertTrue(doc.contains("acresia edible fruit wiring"));
        assertTrue(doc.contains("acresia worldgen configured/placed key resolution"));
        assertTrue(doc.contains("cavenic shroom runtime registry ids"));
        assertTrue(doc.contains("cavenic shroom bounded collision nausea"));
        assertTrue(doc.contains("cavenic shroom bounded shear-harvest helper wiring"));
        assertTrue(doc.contains("cavenic orb drop policy/runtime smoke"));
        assertTrue(doc.contains("cavenic bow runtime registry id"));
        assertTrue(doc.contains("cavenic bow max-damage and damageable-item smoke"));
        assertTrue(doc.contains("cavenic bow repairability with `cavernreborn:cavenic_orb`"));
        assertTrue(doc.contains("cavenic bow no-repair-with-stick smoke"));
        assertTrue(doc.contains("cavenic bow default mode/runtime stack-state smoke"));
        assertTrue(doc.contains("cavenic bow mode cycling order and persistence"));
        assertTrue(doc.contains("cavenic bow sneak-use mode-cycling smoke"));
        assertTrue(doc.contains("cavenic bow RAPID adjusted-shot-power smoke"));
        assertTrue(doc.contains("cavenic bow RAPID higher-velocity vanilla-arrow smoke"));
        assertTrue(doc.contains("cavenic bow RAPID no-extra-durability smoke"));
        assertTrue(doc.contains("cavenic bow RAPID still spawning a vanilla arrow entity"));
        assertTrue(doc.contains("cavenic bow RAPID not inheriting the SNIPE damage multiplier"));
        assertTrue(doc.contains("cavenic bow full-charge SNIPE projectile boost smoke"));
        assertTrue(doc.contains("cavenic bow full-charge SNIPE extra-durability smoke"));
        assertTrue(doc.contains("cavenic bow full-charge SNIPE still spawning a vanilla arrow entity"));
        assertTrue(doc.contains("cavenic bow TORCH vanilla-arrow marker smoke"));
        assertTrue(doc.contains("cavenic bow TORCH valid block-placement smoke"));
        assertTrue(doc.contains("cavenic bow TORCH invalid-target no-placement smoke"));
        assertTrue(doc.contains("cavenic bow TORCH torch-consumption smoke"));
        assertTrue(doc.contains("cavenic bow TORCH no-custom-entity smoke"));
        assertTrue(doc.contains("cavenic bow TORCH not inheriting RAPID or SNIPE behavior"));
        assertTrue(doc.contains("cavenic zombie runtime registry id"));
        assertTrue(doc.contains("cavenic zombie attribute registration smoke"));
        assertTrue(doc.contains("cavenic zombie hostile runtime spawn smoke"));
        assertTrue(doc.contains("cavenic zombie spawn egg resolution"));
        assertTrue(doc.contains("cavenic zombie spawn egg entity-creation smoke"));
        assertTrue(doc.contains("cavenic zombie natural spawn placement registration"));
        assertTrue(doc.contains("cavenic zombie CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("cavenic zombie biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic zombie biome tag resolution"));
        assertTrue(doc.contains("cavenic zombie vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic zombie legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("cavenic zombie legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("cavenic zombie legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic zombie legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic zombie generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic skeleton runtime registry id"));
        assertTrue(doc.contains("cavenic skeleton attribute registration smoke"));
        assertTrue(doc.contains("cavenic skeleton hostile runtime spawn smoke"));
        assertTrue(doc.contains("cavenic skeleton spawn egg resolution"));
        assertTrue(doc.contains("cavenic skeleton spawn egg entity-creation smoke"));
        assertTrue(doc.contains("cavenic skeleton natural spawn placement registration"));
        assertTrue(doc.contains("cavenic skeleton CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("cavenic skeleton biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic skeleton biome tag resolution"));
        assertTrue(doc.contains("cavenic skeleton vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic skeleton legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("cavenic skeleton legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("cavenic skeleton legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic skeleton legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic skeleton generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic creeper runtime registry id"));
        assertTrue(doc.contains("cavenic creeper attribute registration smoke"));
        assertTrue(doc.contains("cavenic creeper hostile runtime spawn smoke"));
        assertTrue(doc.contains("cavenic creeper vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic creeper spawn egg resolution"));
        assertTrue(doc.contains("cavenic creeper spawn egg entity-creation smoke"));
        assertTrue(doc.contains("cavenic creeper natural spawn placement registration"));
        assertTrue(doc.contains("cavenic creeper CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("cavenic creeper biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic creeper biome tag resolution"));
        assertTrue(doc.contains("cavenic creeper legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("cavenic creeper legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("cavenic creeper legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic creeper legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic creeper generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic creeper legacy fuse-time smoke"));
        assertTrue(doc.contains("cavenic creeper legacy explosion-radius smoke"));
        assertTrue(doc.contains("crazy creeper runtime registry id"));
        assertTrue(doc.contains("crazy creeper attribute registration"));
        assertTrue(doc.contains("crazy creeper hostile runtime spawn"));
        assertTrue(doc.contains("crazy creeper spawn egg resolution"));
        assertTrue(doc.contains("crazy creeper spawn egg entity creation"));
        assertTrue(doc.contains("crazy creeper vanilla creeper loot-table baseline"));
        assertTrue(doc.contains("crazy creeper legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("crazy creeper legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("crazy creeper legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("crazy creeper legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("crazy creeper generic-damage baseline smoke"));
        assertTrue(doc.contains("crazy creeper boss-event wiring smoke"));
        assertTrue(doc.contains("crazy creeper boss-bar color/overlay smoke"));
        assertTrue(doc.contains("crazy creeper boss-percent update smoke"));
        assertTrue(doc.contains("crazy creeper tracked-player add/remove smoke"));
        assertTrue(doc.contains("crazy creeper sky-darkening smoke"));
        assertTrue(doc.contains("crazy creeper particle type registry id smoke"));
        assertTrue(doc.contains("crazy creeper particle provider registration source smoke"));
        assertTrue(doc.contains("crazy creeper particle description resource smoke"));
        assertTrue(doc.contains("crazy creeper client-only particle spawn-source smoke"));
        assertTrue(doc.contains("crazy creeper explicit no-natural-spawn baseline boundary"));
        assertTrue(doc.contains("crazy creeper custom fuse/explosion branch remains follow-up"));
        assertTrue(doc.contains("crazy creeper custom lightning/charged/swelling behavior remains follow-up"));
        assertTrue(doc.contains("actual client visual crazy creeper particle feel remains manual"));
        assertTrue(doc.contains("crazy spider runtime registry id"));
        assertTrue(doc.contains("crazy spider attribute registration"));
        assertTrue(doc.contains("crazy spider hostile runtime spawn"));
        assertTrue(doc.contains("crazy spider spawn egg resolution"));
        assertTrue(doc.contains("crazy spider spawn egg entity creation"));
        assertTrue(doc.contains("crazy spider vanilla spider loot-table baseline"));
        assertTrue(doc.contains("crazy spider legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("crazy spider legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("crazy spider explicit no-natural-spawn baseline boundary"));
        assertTrue(doc.contains("crazy spider explicit no-custom-combat / blindness / poison baseline boundary"));
        assertTrue(doc.contains("actual long-run crazy spider orb drop-rate balance is not covered by server GameTests"));
        assertTrue(doc.contains("cavenic spider runtime registry id"));
        assertTrue(doc.contains("cavenic spider attribute registration smoke"));
        assertTrue(doc.contains("cavenic spider hostile runtime spawn smoke"));
        assertTrue(doc.contains("cavenic spider vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic spider spawn egg resolution"));
        assertTrue(doc.contains("cavenic spider spawn egg entity-creation smoke"));
        assertTrue(doc.contains("cavenic spider natural spawn placement registration"));
        assertTrue(doc.contains("cavenic spider CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("cavenic spider biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic spider biome tag resolution"));
        assertTrue(doc.contains("cavenic spider legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("cavenic spider legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("cavenic spider legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic spider legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic spider generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic spider blindness-on-hit runtime smoke"));
        assertTrue(doc.contains("vanilla spider no-blindness comparison smoke"));
        assertTrue(doc.contains("cavenic witch runtime registry id"));
        assertTrue(doc.contains("cavenic witch attribute registration smoke"));
        assertTrue(doc.contains("cavenic witch hostile runtime spawn smoke"));
        assertTrue(doc.contains("cavenic witch vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic witch spawn egg resolution"));
        assertTrue(doc.contains("cavenic witch spawn egg entity-creation smoke"));
        assertTrue(doc.contains("cavenic witch natural spawn placement registration"));
        assertTrue(doc.contains("cavenic witch CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("cavenic witch biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic witch biome tag resolution"));
        assertTrue(doc.contains("cavenic witch legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("cavenic witch deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("cavenic witch legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic witch legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic witch generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic witch legacy same-type/self source-immunity smoke"));
        assertTrue(doc.contains("cavenic witch non-immune source baseline smoke"));
        assertTrue(doc.contains("cavenic witch same-type friendship target rejection smoke"));
        assertTrue(doc.contains("cavenic witch non-friend target baseline smoke"));
        assertTrue(doc.contains("legacy cavenic witch magic-book branch because the inspected legacy `ItemMagicBook` depends on subtype, NBT, capability and spellbook systems that Reborn does not yet implement honestly"));
        assertTrue(doc.contains("cavenic bow enchantment applicability"));
        assertTrue(doc.contains("cavenic bow cavenic item tag resolution"));
        assertTrue(doc.contains("cavenic bow recipe manager resolution"));
        assertTrue(doc.contains("cavenic shroom worldgen configured/placed key resolution"));
        assertTrue(doc.contains("aquamarine tool runtime registry ids"));
        assertTrue(doc.contains("aquamarine tool repairability with `cavernreborn:aquamarine`"));
        assertTrue(doc.contains("aquamarine tool enchantment applicability"));
        assertTrue(doc.contains("aquamarine underwater utility policy/runtime smoke"));
        assertTrue(doc.contains("magnite tool runtime registry ids"));
        assertTrue(doc.contains("magnite tool repairability with `cavernreborn:magnite_ingot`"));
        assertTrue(doc.contains("magnite tool enchantment applicability"));
        assertTrue(doc.contains("magnite brittle max-damage/runtime smoke"));
        assertTrue(doc.contains("magnite no-unintended-Mining-Assist runtime smoke"));
        assertTrue(doc.contains("magnite armor runtime registry ids"));
        assertTrue(doc.contains("magnite armor repairability with `cavernreborn:magnite_ingot`"));
        assertTrue(doc.contains("magnite armor enchantment applicability"));
        assertTrue(doc.contains("magnite armor durability and slot/equippable runtime behavior"));
        assertTrue(doc.contains("hexcite normal and Silk Touch loot paths"));
        assertTrue(doc.contains("randomite curated runtime loot output"));
        assertTrue(doc.contains("hexcite pickaxe enchantment applicability"));
        assertTrue(doc.contains("hexcite armor runtime registry ids"));
        assertTrue(doc.contains("hexcite armor repairability with `cavernreborn:hexcite`"));
        assertTrue(doc.contains("hexcite armor durability and slot/equippable runtime behavior"));
        assertTrue(doc.contains("hexcite armor enchantment applicability"));
        assertTrue(doc.contains("miner_orb runtime registry availability"));
        assertTrue(doc.contains("randomite allowed-drop runtime coverage that now includes miner_orb in the curated pool"));
        assertTrue(doc.contains("miner_orb bonus policy/runtime smoke"));
        assertTrue(doc.contains("ore_compass runtime registry availability"));
        assertTrue(doc.contains("ore_compass target tag resolution"));
        assertTrue(doc.contains("ore_compass scanner nearest-target behavior"));
        assertTrue(doc.contains("ore_compass stored-target state round-trip"));
        assertTrue(doc.contains("ore_compass tracking policy/runtime ids"));
        assertTrue(doc.contains("unsupported/fissured/storage exclusion during ore_compass scans"));
        assertTrue(doc.contains("Mining Assist policy/runtime ids"));
        assertTrue(doc.contains("bounded same-block vein assist with hexcite_pickaxe"));
        assertTrue(doc.contains("no unlock means no assist"));
        assertTrue(doc.contains("sneaking disables assist"));
        assertTrue(doc.contains("fissured_stone exclusion"));
        assertTrue(doc.contains("fissured stone no-drop behavior"));
        assertTrue(doc.contains("fissured stone survival effect behavior"));
        assertTrue(doc.contains("fissured stone creative guard"));
        assertTrue(doc.contains("fissured stone non-destructive behavior"));
        assertTrue(doc.contains("progression policy ids/scores"));
        assertTrue(doc.contains("worldgen configured/placed feature runtime resolution"));
        assertTrue(doc.contains("./gradlew --no-daemon :app-neoforge:runGameTestServer"));
        assertTrue(doc.contains("docker compose run --rm gradle ./gradlew --no-daemon :app-neoforge:runGameTestServer"));
        assertTrue(doc.contains("scripts/runtime-smoke.sh"));
        assertTrue(doc.contains("minecraft:empty"));
        assertTrue(doc.contains("app-neoforge/src/gameteststructures/empty.snbt"));
        assertTrue(doc.contains("GameTestRegistry.register(CavernSpecialOreGameTests.class)"));
        assertTrue(doc.contains("unguarded `GameTestRegistry.register"));
        assertTrue(doc.contains("GameTestHooks.isGametestEnabled()"));
        assertTrue(doc.contains("infrastructure workaround"));
        assertTrue(doc.contains("does not change gameplay behavior"));
        assertTrue(doc.contains("manual client smoke is still needed"));
        assertTrue(doc.contains("actual client-visible needle feel still requires manual smoke"));
        assertTrue(doc.contains("actual worn hexcite armor appearance"));
        assertTrue(doc.contains("actual worn magnite armor appearance"));
        assertTrue(doc.contains("actual Acresia in-world farming feel and growth cadence"));
        assertTrue(doc.contains("actual Cavenic Shroom hazard feel, sparse spread feel and harvest feel"));
        assertTrue(doc.contains("actual Cavenic Bow draw, release and visual client feel"));
        assertTrue(doc.contains("actual Cavenic Zombie renderer/model visual feel"));
        assertTrue(doc.contains("actual Cavenic Skeleton renderer/model visual feel"));
        assertTrue(doc.contains("actual Cavenic Creeper renderer/model visual feel"));
        assertTrue(doc.contains("actual Cavenic Spider renderer/model visual feel"));
        assertTrue(doc.contains("actual Cavenic Witch renderer/model visual feel"));
        assertTrue(doc.contains("actual long-run cavenic spider orb-drop rate balance"));
        assertTrue(doc.contains("actual long-running Cavenic Spider fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-running Cavenic Spider combat/pathfinding feel"));
        assertTrue(doc.contains("actual poison/web-based Cavenic Spider gameplay behavior"));
        assertTrue(doc.contains("actual Cavenic Witch combat, potion-throw and pathfinding feel"));
        assertTrue(doc.contains("cavenic witch legacy ranged-potion runtime smoke"));
        assertTrue(doc.contains("cavenic witch deterministic legacy potion-selection smoke"));
        assertTrue(doc.contains("cavenic witch explicit high-health and low-health potion-threshold smoke"));
        assertTrue(doc.contains("cavenic witch explicit weakness/slowness/harming fallback smoke"));
        assertTrue(doc.contains("cavenic witch deterministic legacy thrown-potion construction smoke"));
        assertTrue(doc.contains("cavenic witch direct non-friend ranged-attack branch smoke"));
        assertTrue(doc.contains("cavenic witch preserved non-witch Raider bridge smoke"));
        assertTrue(doc.contains("cavenic bear runtime registry id"));
        assertTrue(doc.contains("cavenic bear attribute registration smoke"));
        assertTrue(doc.contains("cavenic bear runtime entity spawn smoke"));
        assertTrue(doc.contains("cavenic bear vanilla polar bear loot-table baseline smoke"));
        assertTrue(doc.contains("cavenic bear explicit no-custom-loot boundary from the inspected legacy source"));
        assertTrue(doc.contains("cavenic bear spawn egg resolution"));
        assertTrue(doc.contains("cavenic bear spawn egg entity-creation smoke"));
        assertTrue(doc.contains("crazy zombie runtime registry id"));
        assertTrue(doc.contains("crazy zombie attribute registration smoke"));
        assertTrue(doc.contains("`generic.max_health` clamp"));
        assertTrue(doc.contains("crazy zombie hostile runtime spawn smoke"));
        assertTrue(doc.contains("crazy zombie spawn egg resolution"));
        assertTrue(doc.contains("crazy zombie spawn egg entity-creation smoke"));
        assertTrue(doc.contains("crazy zombie vanilla loot-table baseline smoke"));
        assertTrue(doc.contains("crazy zombie legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("crazy zombie legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("crazy zombie legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("crazy zombie legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("crazy zombie generic-damage baseline smoke"));
        assertTrue(doc.contains("crazy zombie legacy knockback-on-hit melee smoke"));
        assertTrue(doc.contains("crazy zombie deterministic legacy knockback helper smoke"));
        assertTrue(doc.contains("crazy zombie boss-event wiring smoke"));
        assertTrue(doc.contains("crazy zombie boss-bar color/overlay smoke"));
        assertTrue(doc.contains("crazy zombie boss-percent update smoke"));
        assertTrue(doc.contains("crazy zombie tracked-player add/remove smoke"));
        assertTrue(doc.contains("crazy zombie sky-darkening smoke"));
        assertTrue(doc.contains("crazy zombie particle type registry id smoke"));
        assertTrue(doc.contains("crazy zombie particle provider registration source smoke"));
        assertTrue(doc.contains("crazy zombie particle description resource smoke"));
        assertTrue(doc.contains("crazy zombie client-only particle spawn-source smoke"));
        assertTrue(doc.contains("explicit Crazy Zombie natural-spawn deferred boundary"));
        assertTrue(doc.contains("Cavenia-only crazy-roster provider/config path"));
        assertTrue(doc.contains("crazy skeleton runtime registry id"));
        assertTrue(doc.contains("crazy skeleton attribute registration"));
        assertTrue(doc.contains("crazy skeleton hostile runtime spawn"));
        assertTrue(doc.contains("crazy skeleton spawn egg resolution"));
        assertTrue(doc.contains("crazy skeleton spawn egg entity creation"));
        assertTrue(doc.contains("crazy skeleton vanilla skeleton loot-table baseline"));
        assertTrue(doc.contains("crazy skeleton guaranteed cavenic bow equipment smoke"));
        assertTrue(doc.contains("crazy skeleton Infinity enchantment smoke"));
        assertTrue(doc.contains("crazy skeleton mainhand drop chance smoke"));
        assertTrue(doc.contains("crazy skeleton legacy orb-drop event wiring smoke"));
        assertTrue(doc.contains("crazy skeleton legacy orb-drop deterministic winning/losing roll smoke"));
        assertTrue(doc.contains("crazy skeleton legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("crazy skeleton legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("crazy skeleton generic-damage baseline smoke"));
        assertTrue(doc.contains("crazy skeleton boss-event wiring smoke"));
        assertTrue(doc.contains("crazy skeleton boss-bar color/overlay smoke"));
        assertTrue(doc.contains("crazy skeleton boss-percent update smoke"));
        assertTrue(doc.contains("crazy skeleton tracked-player add/remove smoke"));
        assertTrue(doc.contains("crazy skeleton sky-darkening smoke"));
        assertTrue(doc.contains("crazy skeleton explicit no-natural-spawn baseline boundary"));
        assertTrue(doc.contains("crazy skeleton continued vanilla attack-damage baseline, explicit `1024.0` max-health clamp and guaranteed `Cavenic Bow` + `Infinity` equipment stability smoke"));
        assertTrue(doc.contains("crazy skeleton reflection smoke for no particle or custom ranged-AI follow-up overrides beyond the explicit damage, loot, equipment and boss hooks"));
        assertTrue(doc.contains("crazy skeleton explicit custom ranged AI / `EntityAIAttackCavenicBow` deferred boundary"));
        assertTrue(doc.contains("actual client-visible Crazy Creeper boss-bar feel remains manual"));
        assertFalse(doc.contains("crazy creeper particle trail remains out of scope"));
        assertTrue(doc.contains("actual client-visible Crazy Skeleton boss-bar feel remains manual"));
        assertTrue(doc.contains("actual Crazy Zombie client boss-bar visual feel"));
        assertTrue(doc.contains("actual Crazy Zombie client particle-trail visual feel"));
        assertTrue(doc.contains("actual long-running Crazy Zombie melee-knockback feel beyond the deterministic helper/runtime smoke"));
        assertTrue(doc.contains("actual Crazy Skeleton renderer/model visual feel"));
        assertTrue(doc.contains("actual Crazy Spider renderer/model visual feel"));
        assertTrue(doc.contains("cavenic bear natural spawn placement registration"));
        assertTrue(doc.contains("cavenic bear CAVERN-only spawn predicate smoke"));
        assertTrue(doc.contains("cavenic bear biome modifier registry smoke"));
        assertTrue(doc.contains("cavenic bear biome tag resolution"));
        assertTrue(doc.contains("cavenic bear legacy fall-damage reduction smoke"));
        assertTrue(doc.contains("cavenic bear legacy fire-damage immunity smoke"));
        assertTrue(doc.contains("cavenic bear generic-damage baseline smoke"));
        assertTrue(doc.contains("cavenic bear legacy hostile player-target goal smoke"));
        assertTrue(doc.contains("cavenic bear legacy hurt-by-target retaliation smoke"));
        assertTrue(doc.contains("cavenic bear non-player target baseline smoke"));
        assertTrue(doc.contains("cavenic bear legacy melee-goal registration smoke"));
        assertTrue(doc.contains("cavenic bear legacy melee reach smoke"));
        assertTrue(doc.contains("cavenic bear legacy standing-warning threshold smoke"));
        assertTrue(doc.contains("cavenic bear legacy panic-goal registration smoke"));
        assertTrue(doc.contains("cavenic bear legacy burning-only panic-trigger smoke"));
        assertTrue(doc.contains("cavenic bear freeze panic rejection smoke"));
        assertTrue(doc.contains("cavenic bear explicit passive/movement AI equivalence boundary against the inherited modern polar bear base"));
        assertTrue(doc.contains("any broader Cavenic Witch AI-goal or target-selector rewrite beyond the restored ranged-potion slice"));
        assertTrue(doc.contains("actual long-running Cavenic Witch fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-run cavenic witch orb-drop rate balance"));
        assertTrue(doc.contains("actual long-run Cavenic Witch population balance inside CAVERN"));
        assertTrue(doc.contains("actual long-run Cavenic Spider population balance inside CAVERN"));
        assertFalse(doc.contains("Cavenic Spider natural spawning in this baseline slice"));
        assertFalse(doc.contains("Cavenic Witch natural spawning, because that bounded follow-up is still out of scope for the current baseline slice"));
        assertTrue(doc.contains("actual long-run cavenic creeper orb-drop rate balance"));
        assertTrue(doc.contains("actual long-running Cavenic Creeper fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-run Cavenic Creeper population balance inside CAVERN"));
        assertTrue(doc.contains("actual long-run cavenic zombie orb-drop rate balance"));
        assertTrue(doc.contains("actual long-run cavenic skeleton orb-drop rate balance"));
        assertTrue(doc.contains("actual long-running Cavenic Zombie fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-running Cavenic Skeleton fire/lava gameplay feel"));
        assertTrue(doc.contains("actual Cavenic Creeper fuse timing, explosion feel and block-damage behavior"));
        assertTrue(doc.contains("actual long-run Cavenic Skeleton population balance inside CAVERN"));
        assertTrue(doc.contains("actual Cavenic Bear renderer/model visual feel"));
        assertTrue(doc.contains("actual long-run Cavenic Bear drop-rate balance, although the current source inspection found no direct custom bear loot branch beyond the vanilla polar bear baseline"));
        assertTrue(doc.contains("actual long-running Cavenic Bear fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-running Cavenic Bear melee/pathfinding feel"));
        assertTrue(doc.contains("actual long-running Cavenic Bear panic/pathfinding feel"));
        assertTrue(doc.contains("actual long-running Cavenic Bear passive follow/wander/look pathfinding feel"));
        assertTrue(doc.contains("actual Cavenic Bear anger/pathfinding feel"));
        assertTrue(doc.contains("actual long-run Cavenic Bear population balance inside CAVERN"));
        assertTrue(doc.contains("actual long-running Crazy Zombie fire/lava gameplay feel"));
        assertTrue(doc.contains("actual long-run Crazy Zombie orb-drop rate balance"));
        assertTrue(doc.contains("Crazy Zombie custom loot beyond the restored inherited `cavenic_orb` branch"));
        assertTrue(doc.contains("Crazy Skeleton natural spawning, because the inspected legacy path still belongs to the old Cavenia-only crazy-roster provider/config branch rather than the current `CAVERN` biome-spawn pattern"));
        assertTrue(doc.contains("Crazy Skeleton custom loot beyond the restored inherited `cavenic_orb` branch"));
        assertTrue(doc.contains("actual long-running Crazy Skeleton fire/lava gameplay feel"));
        assertTrue(doc.contains("actual client-visible Crazy Skeleton boss-bar feel remains manual"));
        assertTrue(doc.contains("Crazy Skeleton particle-trail follow-up"));
        assertTrue(doc.contains("actual Crazy Skeleton ranged combat feel remains manual / follow-up because the equipment-only slice intentionally does not port `EntityAIAttackCavenicBow`"));
        assertTrue(doc.contains("Crazy Skeleton custom ranged Cavenic Bow behavior remains a separate follow-up boundary even though the guaranteed `Cavenic Bow` + `Infinity` equipment identity is now restored"));
        assertTrue(doc.contains("legacy Cavenic Bow Rapid/Torch custom projectile behavior and client feel beyond the current bounded Snipe, Rapid and Torch slices"));
        assertTrue(doc.contains("actual long-run Cavenic Zombie population balance inside CAVERN"));
        assertTrue(doc.contains("actual underwater aquamarine mining feel"));
        assertTrue(doc.contains("actual brittle magnite mining feel"));
        assertTrue(doc.contains("portal UX"));
        assertTrue(doc.contains("rendering"));
    }

    @Test
    void runtimeSmokeScriptExists() {
        assertTrue(Files.exists(SCRIPT));
        assertTrue(Files.isExecutable(SCRIPT));
    }

    private static Path resolveProjectFile(String first, String... more) {
        Path current = Path.of("").toAbsolutePath();

        for (int i = 0; i < 5 && current != null; i++) {
            Path candidate = current.resolve(Path.of(first, more));
            if (Files.exists(candidate)) {
                return candidate;
            }
            current = current.getParent();
        }

        throw new IllegalStateException("Could not resolve project file: " + Path.of(first, more));
    }
}
